### ISSUE TITLE
Doesn't work in IE

### ISSUE THREAD

**Issue by bishopandco** [chrislgarry/Apollo-11#100]
Can't ship.

**Comment by Alhadis** [comment]
> Can't ship

<img src="https://cloud.githubusercontent.com/assets/2346707/16660954/fa9daa96-44b3-11e6-9ecf-cc998ba52056.jpg" alt="topkek" />

**Comment by gohackfelipe** [comment]
LOL

**Comment by niutech** [comment]
False. It works in all modern browsers, including IE: http://svtsim.com/moonjs/agc.html
