### ISSUE TITLE
Make refactoring

### ISSUE THREAD

**Issue by hellboy81** [chrislgarry/Apollo-11#102]
Goal: Make code more maintainable and debuggable

Guidelines:

- Refactor to functions
- Write some manual tests
- Code cleanup
- Refactor to objects
- Write some unit tests
- Try to isolate with mocks and stubs
- Refactoring to patterns
- Write integration tests
- Write simulation environment
- Write acceptance tests

**Comment by lassombra** [comment]
simulation environment complete: http://svtsim.com/moonjs/agc.html

**Comment by chrislgarry** [comment]
Simulation environment: https://github.com/rburkey2005/virtualagc, along with everything else you could ask for :)
