### ISSUE TITLE
Plugin for Vim

### ISSUE THREAD

**Issue by webknjaz** [chrislgarry/Apollo-11#104]
well.. you know

**Comment by ohommes** [comment]
How about looking at the original github source and see there is already many syntax highlighting for years and the capability to run in CodeBlocks and single step Apollo 11 code.

https://github.com/rburkey2005/virtualagc/tree/master/Contributed/SyntaxHighlight

**Comment by chrislgarry** [comment]
@webknjaz check out @ohommes 's link. They've got the whole enchilada.
