### ISSUE TITLE
Issues are getting out of hand

### ISSUE THREAD

**Issue by oldmud0** [chrislgarry/Apollo-11#109]
Enough with the jokes already, guys. They were nice and I was playing along the first few times but now the jokes are seeping into the pull requests and so it's difficult to do any real work on the repo.

I suggest disabling issues for now until popularity cools down.

**Comment by howditgetburned** [comment]
Why would work be done on it? it's here for preservation, not improvement.

**Comment by oldmud0** [comment]
I was only joking, did you not see the smile on my face?

**Comment by pedromorgan** [comment]
I think the jokes are done...

and actually honestly.. I've never programmed and FPGA, but all fun aside, I think all the curious worms are coming out the woodwork, and maybe even all of u hackers making the code run, and ardunois, rpi, ttl, cmos, fpga, leds, et all flashing light in a REAL sim with hardware would be fun, maybe..
Even get down to hardware/software + engineering..

http://www.webaugur.com/bazaar/53-what-if-operating-systems-were-airlines.html

Love the last one = Linux Airlines  = FOSS = fun for all..

**Comment by pedromorgan** [comment]
Can I also suggest creating labels..such as
"Humour" "typo", "faq", "proposal" etc..

**Comment by chrislgarry** [comment]
@pedromorgan Great idea. I've create a new humor label, and will create others as necessary. Thanks for the tip. @oldmud0 I think it's important for everyone to be able to have fun even though we are trying to maintain a serious repo of the original code. I don't mind combing through the jokes. I'll just label them as jokes and resolve so we can keep an eye on issues with digitization and missing files. Thanks.

**Comment by oldmud0** [comment]
I felt that we were kind of getting overrun by joke issues. Sorry for overreacting... and playing down my mistake as a joke...

**Comment by chrislgarry** [comment]
@oldmud0 oh, we definitely are getting overrun by joke issues :) no worries. I initially was going to do that then realized people initially came for the fun, but stayed to help contribute.
