### ISSUE TITLE
E.T. the Extra-Terrestrial ( from movie ) installed this in his bike?

### ISSUE THREAD

**Issue by gohackfelipe** [chrislgarry/Apollo-11#110]
Please, i need know this :)

![et_moon](https://cloud.githubusercontent.com/assets/15708865/16745112/c0b8facc-478a-11e6-86c3-24f1871e4f82.jpg)

**Comment by gkal19** [comment]
Brasileiro é foda!
PQP

**Comment by feliphebueno** [comment]
Br sendo Br. 
huehuehue

**Comment by chrislgarry** [comment]
Either that, or it may have been installed in the tip of his finger.
