### ISSUE TITLE
How and What to contribute?

### ISSUE THREAD

**Issue by nitram509** [chrislgarry/Apollo-11#112]
This is an interesting project, awesome.

I would like to contribute, but I have some questions, where to start ...

* I see the folk on http://www.ibiblio.org/apollo/ have some JPEG fotos and already provide source files.
   * are these already complete?
   * are there errors in? how do you know?
   * are there source files missing?
   * is there an overview, which files are potentially OK or buggy?
   * where should I start: at the images or at the html files?
* why are there different file extensions .agc vs. .s  (just for GitHub syntax coloring makes no sense to me, as one should go the the original naming conventions)?
* are there any tools / scripts available, already used for transcripting?
* whats the goal of this project?
   * get 100% correct, transcripted sources?
       * what level are we currently?
   * fork it and make it runnable on modern compilers?`
   * do refactoring? apply clean code rules?

I hope you can enlighten me ... and maybe provide something like 'HOW-TO-CONTRIBUTE.md' so that others my follow ;)

Thanks in advance

**Comment by oldmud0** [comment]
Readme says:
> The goal is to be a repo for the original Apollo 11 source code.

Basically preserve as much and as accurately as possible the computing components of the Apollo 11, and no new stuff allowed. Transcription errors ought to be fixed, even if the transcription was trying to correct a typo. The people at ibiblio have mostly done the job for us already, but the task now is more of cleaning everything up and make it usable for anyone who wants to run a simulated mission on whatever platform/simulator they want.

**Comment by oznogon** [comment]
The volunteering page on Ron Burkey's project is probably a good starting point, especially the sections on [Code Conversion or Proofing](http://www.ibiblio.org/apollo/volunteer.html#Code_Conversion).

**Comment by chrislgarry** [comment]
The goal is to be an accurate reflection of the original code. I'm not concerned with building. The folks at Virtual AGC have done an excellent job with that already: https://github.com/rburkey2005/virtualagc. The code they have is accurate as well, less some typos in the original comments. The fixups in this repo will be merged by @rburkey2005 when this repo reaches a steady state. The .s for syntax highlighting makes sense to me. Those images a ibiblio are complete, and that is what we are using for reference. There may be source files missing in this repo, and I am going to merge them in. Start with the images, not the html files. Someone has kindly updated the links in the README to point to the images. If you would like to add a how to contribute section in the README, I'd gladly merge that in.
