### ISSUE TITLE
FAQ Idiot Questions

### ISSUE THREAD

**Issue by pedromorgan** [chrislgarry/Apollo-11#114]
Idea here is to solve curiosus questions..

**Comment by pedromorgan** [comment]
Is there a PID controller ?
https://en.wikipedia.org/wiki/PID_controller

**Comment by pedromorgan** [comment]
What is the clock and sample rates of pressure from "things"..
How is a2d done ??

**Comment by pedromorgan** [comment]
FPGA is an electronics sim.. Can I attempt to write at least the ins and outs and even create the whole scenario in my bedroom ?? YES.. u can.. at last ..

**Comment by chrislgarry** [comment]
@pedromorgan there are many PIDs in the code for different components of the system. I'm sure different components work at different frequencies. There are many DAC/ADCs in the code as well for all of the hardware sensors to interface with the AGC. And yes, you can recreate this from your bedroom :) Virtual AGC has done that for us, so you can use that as a reference point: https://github.com/rburkey2005/virtualagc. If you'd like to create a FAQ, feel free to submit a PR.
