### ISSUE TITLE
Discrepancy in punctuation used.

### ISSUE THREAD

**Issue by wopian** [chrislgarry/Apollo-11#115]
Reviewing the big PR, I've noticed in several places where the source images have different punctuation than what is used in the digitalised version.

E.g i've seen a few places where `:TEXT:` was written, but as `'TEXT'` in the digitalised version.

[055-Pg0369](http://www.ibiblio.org/apollo/ScansForConversion/Comanche055/0369.jpg)
![](http://i.imgur.com/sHrzoby.png)
![](http://i.imgur.com/s2z9deD.png)

Dashes are also converted to double dashes too. (099-Pg0619), while other times they're converted as a single dash. (055-Pg0526)

dash -> --
![](http://i.imgur.com/aGQPZ39.png)
![](http://i.imgur.com/IJF6hrv.png)

dash -> -
![](http://i.imgur.com/WNJVFV3.png)
![](http://i.imgur.com/35SBk9N.png)

Do we keep them as is, or convert them to :TEXT:?

**Comment by chrislgarry** [comment]
@wopian thanks. Use the original as the authoritative source. If any changes happen to break build, that's fine; that's what Virtual AGC is for.

**Comment by wopian** [comment]
So -- -> - and :TEXT: digitalised to 'TEXT' back to :TEXT:?
