### ISSUE TITLE
kalman filter is exactly exist

### ISSUE THREAD

**Issue by NanYoMy** [chrislgarry/Apollo-11#116]
well, i had happen to know KALMAN FILTER is popular for its usability in apollo-11. and i had check this git. finally i find a file named KAILMAN_FILTER. that's really awesome! it just like i had find a old treasure from our old ancestors.

**Comment by chrislgarry** [comment]
@NanYoMy In fact, the Apollo projects were the first publicly known application of the Kalman Filter :)

**Comment by NanYoMy** [comment]
great job!

**Comment by oldmud0** [comment]
Sorry to say, but Kalman passed away about two weeks ago.
