### ISSUE TITLE
Got this when trying to launch...

### ISSUE THREAD

**Issue by J7mbo** [chrislgarry/Apollo-11#12]
![bsod](https://upload.wikimedia.org/wikipedia/commons/3/3b/Windows_9X_BSOD.png)

Any ideas?

**Comment by gooh** [comment]
It requires the EU membership module. You are from the UK. Sorry.

**Comment by MinnDevelopment** [comment]
Where is the any button?

**Comment by J7mbo** [comment]
Closing as lack of EU membership was the issue.
