### ISSUE TITLE
Cant render landing on Moon, as it was 20 July 1969

### ISSUE THREAD

**Issue by Symbian9** [chrislgarry/Apollo-11#126]
Try use this project in Blender for render historical landing, but still have not any results.
Any ideas?
![Apollo 11 on Moon](https://upload.wikimedia.org/wikipedia/commons/1/1e/Apollo_11_first_step.jpg)

**Comment by rougetimelord** [comment]
Have you tried all keyboard shortcuts available on the DSKY?
