### ISSUE TITLE
Update to go to Mars

### ISSUE THREAD

**Issue by deboc** [chrislgarry/Apollo-11#127]
Nice release !
I tested the code and it landed to the Moon properly. But can someone explain me how to fine tune it to go to Mars ? Is it some config file to update ?
Thanks,

**Comment by aralroca** [comment]
Hey! I don't have so much idea about assembly but I'm interested and how you tested the code  👍  I want to test it also. Thank you so much!

**Comment by Zerquix18** [comment]
Delete system32 in order to overclock and then re-compile with the flag `--planet=Mars`.

**Comment by TheMengzor** [comment]
And don't forget to put in in `C:\Program Files\` instead of `C:\Program Files (x86)\`

**Comment by akring** [comment]
It's quite simple,just rename the "GoToMoon" function with the new name "GoToMars".
This worked for me,and I will visit the Sun this evening,because it's too hot in daytime.

**Comment by raoshaoquan** [comment]
Interesting ~

**Comment by chrislgarry** [comment]
This will be resolved in [Orion](https://www.nasa.gov/exploration/systems/orion/index.html).

**Comment by oldmud0** [comment]
Orbital parameters of Earth are fairly similar to that of Mars so it's best to photocopy the GOTOEARTH pages and change a few numbers.

**Comment by nexteve** [comment]
Interesting ~

**Comment by brave-orange** [comment]
good idea
