### ISSUE TITLE
"Smarty" migration: convert software to PHP in order to run using Apache

### ISSUE THREAD

**Issue by mfbiux** [chrislgarry/Apollo-11#128]

**Comment by aralroca** [comment]
Why PHP? I think it's not the best option for this propose. Has been programmed in Assembly to use the speed benefits in the space. If some smarty migration is needed to a modern language I think that Scala, for example, is a better option.

**Comment by ddemuro** [comment]
Migrate to C++, you get the best of all worlds haha.

**Comment by Zerquix18** [comment]
That's a little hard. How should we call the function to go to the moon? `go2themoon()` or `gotothemoon()` or maybe `go_to_the_moon()` but we can also call it `moon_go()`

**Comment by ufolux** [comment]
Because PHP is the best PL all over the world.

**Comment by VhatAmI** [comment]
@Zerquix18 how about `setDestinationMoon()` or `moonVoyage()`?

**Comment by gersilex** [comment]
`goto(10)` because "moon" is enumerated as unsigned int somewhere else, to keep it simple and efficient.

**Comment by Alhadis** [comment]
[There's only one language that this should've been written in](http://moonscript.org/).

**Comment by ChenDongnan** [comment]
I think Swift will be a better choice

**Comment by rmorandi** [comment]
+1

**Comment by leleonam** [comment]
Java, maybe?!

**Comment by Ayanda-D** [comment]
Has to be [Erlang OTP](http://www.erlang.org/) - & having some of those interrupt service routines being carried out within concurrent erlang processes => multiple control operations taking place at the same time :)

**Comment by borfast** [comment]
I think they already tried PHP for Apollo 13 but the mission didn't go too well due to some confusion over function arguments order, or something...

**Comment by tjchambers** [comment]
@borfast - what I heard was it had to do with nameSPACEing - not function argument order. The function argument theory was easily discounted when they discovered who was in the left hand seat at the time of stir. Or was it the right hand seat? I any case I am sure order is irrelevant.

**Comment by BrotherPhil** [comment]
Could call the function time.addTicket ("Moon"), though that may only work for routings via Satellite 2.

**Comment by MacRiada** [comment]
Needs a [DRAKON](https://en.wikipedia.org/wiki/DRAKON) port. Дружелюбный Русский Алгоритмический язык, Который Обеспечивает Наглядность or "friendly Russian algorithmic language that provides clarity", deveoped for the Soviet Buran reusable spacecraft programme.

**Comment by tibu** [comment]
the architecture should be microservice of course. http://moon/getLandingAvailability
