### ISSUE TITLE
Just like NASA, I was able to perform a fake "moon landing" on my backyard. But the flag was not floating in gravity.

### ISSUE THREAD

**Issue by nitinprakash96** [chrislgarry/Apollo-11#135]
>

**Comment by pomoke** [comment]
run 
> flag.float()

**Comment by kriptonis** [comment]
check the dust clouds on your rover's wheels to assess if landing was indeed fake or not.
There is a distinct pattern that dust will do in near-zero gravity that is impossible to reproduce on Earth.
For documentation see examples of such pattern in Apolo 11's photos.
