### ISSUE TITLE
Rewrite in Rust

### ISSUE THREAD

**Issue by jaksi** [chrislgarry/Apollo-11#14]
Would this project be interested in moving to Rust? It's the perfect language for such a mission critical software.

**Comment by AyrA** [comment]
I suggest node.js with Redis and MongoDB so it is webscale.

**Comment by bhean** [comment]
Move to AWS... obviously clouds are closer the space than the rocket platform... you can save lot of money!
xDD

**Comment by NikolayIT** [comment]
Not enough jQuery...

**Comment by slbug** [comment]
why @steveklabnik not here yet?

**Comment by funny-falcon** [comment]
Go(lang) provides readable sources, so project will have painless evolution.
And it has great concurrency primitives, so dealing with a lot of sensors, doing a lot of concurrent tasks is not a problem for.
Given every release GC pause is decreasing, it will be suitable for spaceships at the moment this project will be rewritten.

**Comment by funny-falcon** [comment]
I really do believe, Neil Armstrong could not land on moon without Go.

**Comment by welociraptor** [comment]
You are suggesting obsolete languages. Pony is designed to be an open-source, object-oriented, actor-model, capabilities-secure, high performance programming language. http://www.ponylang.org/

**Comment by thekemkid** [comment]
@welociraptor Yes, but is it webscale?

**Comment by howardjp** [comment]
MongoDB is webscale.

https://www.youtube.com/watch?v=b2F-DItXtZs

**Comment by funny-falcon** [comment]
It ought to be SPACESCALE for this project!

**Comment by Sword-Smith** [comment]
Why has no one suggested PHP yet?
