### ISSUE TITLE
Patching Apollo-11! What is this!

### ISSUE THREAD

**Issue by TurkeyMan** [chrislgarry/Apollo-11#142]
You can't patch the code, it's shipped! ;)
No seriously,  why?

**Comment by ksHKK** [comment]
*

**Comment by chrislgarry** [comment]
@TurkeyMan what we are fixing are the typos that were made when the original Apollo 11 source code was transcribed from its original paper copies to the digital format we have here.

**Comment by TurkeyMan** [comment]
:+1:
