### ISSUE TITLE
Do not select P01 during flight 8.x

### ISSUE THREAD

**Issue by adam-s** [chrislgarry/Apollo-11#15]
### Problem/Motivation
Margaret Hamilton's daughter was playing in the simulator command module and [somehow ran the P01 prelaunch program](http://www.wired.com/2015/10/margaret-hamilton-nasa-apollo/) during simulated flight and crashed the entire system. 

### Proposed resolution
Add error handling and validation because humans make mistakes and lie #9. Although this issue was brought to the attention of higher ups at NASA, astronaut Jim Lovell selected P01 in flight during the Apollo 8 mission crashing the entire system.

While we are adding error handling we should also implement asynchronous programming and priority scheduling to prevent the system from crashing during mission critical tasks.

**Comment by thefailtheory** [comment]
That right, i didn't test it yet but it seems that when you look at MAIN.s it ask you to take a look at this file that contain the list of all verbs and nous
https://github.com/chrislgarry/Apollo-11/blob/master/ASSEMBLY_AND_OPERATION_INFORMATION.s
anyway, if you say this it's just unbelivable what happened to Apollo 8 mission
