### ISSUE TITLE
Readme of Traditional Chinese

### ISSUE THREAD

**Issue by aleen42** [chrislgarry/Apollo-11#153]
https://github.com/aleen42/Apollo-11

**Comment by oldmud0** [comment]
uhh... no?

**Comment by aleen42** [comment]
Oh @oldmud0  I see.

**Comment by wopian** [comment]
I would suggest splitting it out into it's separate README file - i.e `README.zh_tw.md`. This would avoid cluttering the README and make it easier to expand to more translations in the future.

[github-cheat-sheet](https://github.com/tiimgreen/github-cheat-sheet) is a repo that's done a good job at supporting this.

**Comment by aleen42** [comment]
@wopian Yup, that's a good choice, and I'll give out a pull request soon.

**Comment by aleen42** [comment]
@oldmud0 @wopian @chrislgarry Simplified Chinese is almost same as the Traditional one, and I will give another pull request for it.
