### ISSUE TITLE
[Meta] Relabel issues

### ISSUE THREAD

**Issue by oldmud0** [chrislgarry/Apollo-11#158]
Some funny stuff is labeled as "humor" and others as just "invalid." I'll close this when I finish changing the labels.

**Comment by chrislgarry** [comment]
Thanks. Made the label after I realized I could do so -__-

**Comment by chrislgarry** [comment]
I took care of the rest. There were some issues marked as questions which should have been humor.

**Comment by oldmud0** [comment]
Oh thank you.
