### ISSUE TITLE
Query about blank lines

### ISSUE THREAD

**Issue by wopian** [chrislgarry/Apollo-11#159]
After checking about 10% of the CONIC_SUBROUTINES.agc file, I've noticed that the digitisation is only using empty lines on lines marked as `R0000` and ignores fully blank lines. However, outside of this file I've noticed in many places these fully empty lines have sometimes been included - the usage seems pretty inconsistent.

Which would be best to make this as accurate to the source files as possible?

cc @chrislgarry @rburkey2005

---

Example ([Page 1266](http://www.ibiblio.org/apollo/ScansForConversion/Comanche055/1266.jpg)

This page has a mixture of empty lines marked with `R0000` and empty lines with no line number.

![](http://i.imgur.com/nQWrqUH.png)

The raw digitalised file has only used the `R0000` empty lines (plus an erroneous blank line within the list)

![](http://i.imgur.com/hTsVwVn.png)

Vs. this version that includes the empty lines with no line number

![](http://i.imgur.com/IIn85RH.png)

**Comment by oldmud0** [comment]
I believe that lines that do not have a corresponding line number are not part of the source code, so they should not be included. I think the final goal here is that every line number in a file corresponds to the line number in each page, so it's a 1:1 transcription. Of course though, we leave for last the actual removal of the page numbers from the code.

**Comment by chrislgarry** [comment]
Empty lines in the original should be empty lines here. Empty lines with a number at the beginning should be empty lines with a number at the beginning. The scans are the ground truth. This could be a bit of work. Lets use the broken windows theory and just make such fixes whenever we touch a file that happens to have this issue. Once we work our way through higher priority issues, we can focus on these. If we are at that point, then by all means. After a couple weeks, I am just now catching up on where we are at with everything.

**Comment by wopian** [comment]
@oldmud0 @chrislgarry we'll never get a 1:1 transcription.

The source code has multiple lines of code for some lines - i.e line 0120 has 01201, 012011, 01202.

[Page 1028](http://www.ibiblio.org/apollo/ScansForConversion/Comanche055/1028.jpg)
![](http://i.imgur.com/yLw81a7.png)

Other pages have duplicated line numbers - where one has code and another is 'empty'

{Page 1029](http://www.ibiblio.org/apollo/ScansForConversion/Comanche055/1029.jpg)
![](http://i.imgur.com/6OyUwcI.png)

**Comment by oldmud0** [comment]
Hmm.. I guess it comes down to best judgment.

**Comment by jimlawton** [comment]
Page 1028: I always assumed that these were cards that had been inserted into the source deck, and this numbering was used to avoid having to renumber subsequent cards, but I could be completely wrong about that. 
 
The images are scans of "listings" not source code, i.e. they are one of the *outputs* of the GAP cross-assembler (along with object code, etc).

With respect to 2 lines with the same number, e.g. the page 1029 example above, the second page 0174 is not part of the source deck. The assembler is indicating that card 0174 in the source deck occupies 2 words in memory.

Finally, with respect to the blank lines, I would keep them. Possibly the original source deck had linefeed cards that are not otherwise represented in the listing (we'll never know I guess), but it does look like the vertical spacing is intentional.

**Comment by rburkey2005** [comment]
From my standpoint, question like this revolve around /criteria/, and I 
admit I'm not fully clear on what your criteria for the work that's 
being done are.  For example, my criteria for the original 
transcriptions we did was that the binary produced by my assembler, 
yaYUL, had to 100% byte-for-byte match the binaries produced by the 
original project's assembler -- which as Jim says was GAP by the time of 
Apollo 11, though it was originally a different program, YUL. That, 
then, served to demonstrate that the operational portion of the source 
code was correct.  Given that that was accomplished, I then wanted the 
comments in the source code to match 100% as well, but we only had 
limited resources and so were not able to always accomplish that.  As 
far as blank lines are concerned, I was happy with 1 line, for 
readability, but I had no interest in multiple blank lines in a row, and 
left them out.  So by /my/ criteria, if you're working to cross-check 
yet once again the source code, as well as to correct the comments, and 
if it still assembles 100% byte-for-byte correctly, you're doing all I 
would have hoped for.

As Jim also points out, the online page scans are not the original 
source code, they are a printout from GAP.  yaYUL now produces similar 
printouts, except in much more readable form, with colorized syntax 
highlighting and hyperlinks, all of which are posted online already 
(see, for example, 
http://www.ibiblio.org/apollo/listings/Comanche055/MAIN.agc.html). 
They're not formatted quite the same as GAP did, for practical reasons.  
I don't recall precisely, but I expect yaYUL is going to remove any 
superfluous material (such as more than one blank line in a row) from 
its final printout anyway.  Keep them or not, as you wish, as long as 
(according to my criteria) the binary output of the assembler is 100% 
correct.  yaYUL will also, I think adjust the column alignment of the 
operand and comment fields.

As I understand it, GAP didn't operate directly from the card decks.  I 
believe that the cards were read into a magnetic-tape memory library, at 
which point the cards became irrelevant until corrections had to be 
made, and assemblies were all done from the material stored in the 
library.  Whether this process preserved extraneous info like extra 
blank lines, I can't say.

Jim says we'll never know about the original intentions behind the blank 
lines, but we can probably find out if you're really excited to know.  
We can ask Hugh Blair-Smith, one of the original programmers, and the 
writer of GAP.  I'll do that, if you like, but I'd like a fairly 
precisely-worded question before doing so. If the question just "should 
we keep them or not?", I don't think he'll have any more insight into 
the matter than I do ... but perhaps he would.

-- Ron

**Comment by oldmud0** [comment]
If these are just GAP printouts, then where is the original source code?

**Comment by jimlawton** [comment]
It was originally on punch card decks, then at some point in 1965 or so, they moved it to magnetic tapes. The actual builds for the flights were done from those mag tape libraries. I guess those mag tapes were lost a long time ago. The printouts survived because people kept them as souvenirs.

**Comment by rburkey2005** [comment]
If you're responding to what Jim Lawton and I said, perhaps I wasn't 
clear.  The page images posted at VirtualAGC are scans of printouts from 
GAP.  The *.agc files are the transcriptions from VirtualAGC that 
represent the source-code parts of those printouts.  The original source 
code existed only on cards and in tape memory banks, never in giant 
printouts, and is therefore nowhere at all any longer, presumably.  I 
believe that the original programmers actually wrote the source code out 
on paper, possibly on something like graph paper, and then handled it 
over to a room full of WAFs who operated the keypunch machines and 
created the cards, which were read into the mag tape library.

The point I was trying to make, ineptly, is that the formatting you see 
in the GAP printouts existed only in the GAP printouts, and presumably 
only partially reflects whatever material the original programmers wrote 
down on paper, so preserving the formatting for posterity doesn't really 
reflect the programmers' experience.  I think.

-- Ron

**Comment by proudindiv** [comment]
The original programmers worked mostly with the GAP printouts.  They only
went to the card decks to submit changes.  I programmed in that era with
similar assembler programs.  I don't know about the MIT programmers, but we
programmers made the changes to the card decks ourselves and submitted or
ran them ourselves.  Having another party punch the cards only adds another
layer for errors and misunderstanding.  The assembler printouts were also
heavily used in debugging when referencing the contents of memory during
simulations.  In our system, when the program failed, it produced a core
dump listing of the contents of memory at the time of the failure.  I'm
sure the Apollo programerss did something similar on their simulation
systems.  They also used a DSKY to examine memory referring to the
generated octal on the listing when simulating on the real computer.  The
assembler printout is the only link to what the computer is doing.

**Comment by rburkey2005** [comment]
My apologies:  I should have refreshed my memory about the WAF thing 
before saying it.  That wasn't an AGC thing at all (as has been pointed 
out), but was rather something that was told to me by an MSC intern, 
about his experiences in 1966 working on the engineering simulations of 
various burns.  To quote him, "Tedious work but it worked when we tried 
it in the sim.  The most fun part was taking the coding sheets to the 
'swamp' for the keypunch operators to build the card decks to be taken 
to the computer center.  You see, the 'swamp' was a tiered auditorium 
with many young women at keypunch machines on the tiers.  Of course, we 
young engineers would enter the room at the front at what was the focus 
of the tiers--one felt a little like a bull at the rodeo 
auction--without the brands on our butts, of course.   For a 21 year old 
it was a hell of a way to meet women--bored, horny women...." :-)

I guess my imaginary picture of that auditorium remained in my mind long 
after the other details had vanished, for some reason.

**Comment by wopian** [comment]
>As far as blank lines are concerned, I was happy with 1 line, for
readability, but I had no interest in multiple blank lines in a row, and
left them out.  So by /my/ criteria, if you're working to cross-check
yet once again the source code, as well as to correct the comments, and
if it still assembles 100% byte-for-byte correctly, you're doing all I
would have hoped for.

What I've been doing when cross-checking the files is: fixing typos in the comments, modifying the positioning of comments to better match what was shown in the images/GAP printouts - mainly just the paragraphs - and adding (or in the rare case removing) blank lines by however many were shown on the printouts.

>Jim says we'll never know about the original intentions behind the blank
lines, but we can probably find out if you're really excited to know.
We can ask Hugh Blair-Smith, one of the original programmers, and the
writer of GAP.  I'll do that, if you like, but I'd like a fairly
precisely-worded question before doing so. If the question just "should
we keep them or not?", I don't think he'll have any more insight into
the matter than I do ... but perhaps he would.

My question was indeed a simple "should we keep then or not" in the original post, however since then and looking back other past files I've cross-checked I came to notice that the single lines were mostly used for general formatting and legibility - such as separating each label and their instructions (although this appears to be inconsistent), while the double/triple lines were mainly splitting different sections of the documentation up. Page 1263 of the Comanche055 is one of the better examples of this: http://www.ibiblio.org/apollo/ScansForConversion/Comanche055/1263.jpg.

So my question is now: Was the formatting of the comments (with the multiple line breaks) the original intentions of the programmers who wrote the code, or formatting artifacts introduced in the keypunching process. As if it was intentional i'd rather these line breaks be restored.

**Comment by rburkey2005** [comment]
I'll pass your question along to Hugh Blair-Smith.  I have contact info 
for a few of the other developers, but he's the only one I have any kind 
of regular contact with, so that's really the best I can offer.  I'll 
let you know if/when he weighs in.

It has been so many years now that I had actually forgotten why I wasn't 
very keen on keeping the blank lines.  I think what it came down to is 
that having a bunch of extra blank lines works much better on paper than 
it does on the computer screen.  If you look at a printed page with 5 
lines of text at the top and 50 blank lines below it, you realize that 
the blanks are formatting.  But this source code will mostly be viewed 
in a text editor, and if you encounter 50 blank lines in a text editor 
--- e.g., a completely empty page and no visual clue as to why it's 
there --- it just looks like your file is broken.  Or for that matter, 
if you print out a copy, but the number of lines per page isn't 
precisely equal to the original, it just looks bad.  In partial 
compensation for removing the blanks, of course, I split the source code 
into individual files, so that the files take the place, to some extent, 
of the section breaks.  But on the other hand, preserving the blank 
lines but only up a a maximum of 4-5 of them wouldn't be so bad in that 
respect.

**Comment by rburkey2005** [comment]
Okay, I think you'll be please with this.  Here is Hugh's answer in 
full, and I will refrain from expressing further personal opinions on 
the topic.  Needless to say, I suppose, the yaYUL assembler does not use 
the column 1 characters Hugh mentions, and does not attempt to duplicate 
any of this specific formatting, and instead applies a colorized syntax 
highlighting.  Enjoy!

    One question is whether amanualpage break falls into your definition
    of "blank lines" in which case there could be any number of
    consecutive"blanklines" up to fifty-something for a very short
    page.I believe theonly way such page breaks were put in the code was
    to begin a remarks card with P instead of Rin column 1, thereby
    forcing it to be the first line on a new page.That certainly implied
    a fairly major change of topic. On the other hand, it appears this
    info isn'tentirelylost becausesomebody has put in what looks like a
    full set of page number indicators in the form/#//#//Page 1234/.They
    look as if they appear at the originalautomaticpage breaks in most
    cases (as they should dobecause the symbol table and other indexy
    things are keyed to page numbers), but for manual page breaks they
    seem to appear after the page-top remarks cardsand just ahead of the
    first non-remark code on that page.A (small) pity, that, since
    itwould have expressedthe purpose of the manual page breaksbetter if
    it had preceded the page-top remarks.But not a big thing.

    Within the code on a page, the blank lines were put in under control
    of an unprinted digit in card column8, between the card numberfield
    and the location field. A 2 there forced a double-space (1 blank
    line)after its card, a 3 there forceda triple-space (2 blank lines),
    and I'm pretty sure the values 4 through 8 were never used,
    thoughthey weredefinedand supported.Double-spacingseparated groups
    of assembler control commands from actual code-generating lines, or
    within codegenerally meant that the line above it (often a branch
    instruction) was not always followedat run timeby the line below it,
    and triple-spacing was generally a small change of topic, not big
    enoughto inducea manual page break.So yes, triple-spacing did mark
    differences in sections of code, but I don't see that much was lost
    by reducing them to double spacing.If your friends would like to
    restore the triple-spacings, they could(aside from peeking at sites
    with scanned hard-copy pages) limit their attention to blank lines
    that are preceded by a non-remark and followed by a remark
    line.Within that set, an educated guess as to where topic breaks
    occur will get pretty close.

    Having said all that, if you think there were any non-page-break
    cases with more than two consecutive blank lines, I like to hear
    about them.

    And yes, I am indeed the right fellow to ask. These minutiae were
    part of my determination to make the code easy to read.I can't think
    ofany reasons for blank lines beyondthose stated above, and I'd be
    pretty surprised if anybody else could.

    The reason for providing double-spacing and triple-spacing logic was
    to make it unnecessary to have physical blank cards in the decks,
    which were frequently pulled out, carriedto and from keypunches, and
    put back.A Steelcasefile drawerof 3000 punched cards was a heavy mutha.

    You can see evidence of the above in the fact that in the normal
    flow of card numbers, the one after such a spacing isgenerally1 more
    than that of the card before--no missing numbers due to spacing.But
    having said that, I have to explain why the card numberfollowing a
    remark over 72 columns wide is generally 2 more than the one you can
    see on the remark line. That's because the only way tomake such a
    remark was to have a second card, with a 9 in column 8, whose
    columns 9-48 were printed in print positions 81-120 of the previous
    line.That feature was called "right print."

    Hugh

-- Ron

**Comment by proudindiv** [comment]
Thanks, I was just thinking about suggesting something like that.  I had
counted characters on a line and wondered about how the 81-120 positions
were entered.  Is there a reference for pseudo op codes, such as "END" for
the end card of the deck, that affected the listing and operation of the
assembler but didn't print in the listing?

**Comment by rburkey2005** [comment]
No, no formatting-related pseudo ops are supported by yaYUL.  You have to realize that there's no manual describing any of that stuff, or even some very basic aspects of the syntax of the assembly language. (At least as far as I could find out at the time.)  Nor did I have any AGC developers to ask about it until long afterward.  So most of syntax was reverse engineered by me, and only to the extent of getting the correct binary produced in yaYUL, which was my be-all and end-all.  And to this day there is still a way (the SBANK pseudo-op) in which yaYUL fails to comply, and needs extra SBANKs to be inserted manually.
--Ron

Sent on my Virgin Mobile Samsung Galaxy S® 5

-------- Original message --------

**Comment by proudindiv** [comment]
Actually, you did a great job and I'm very thankful I stumbled onto your
work.

I don't have too much at stake in the details of the formating.  Your
response
from Hugh Blair-Smith was the most wonderful.  The whole project has brought
back lots of memories for me.

I'm about to start reverse engineering the algorithms used by the code.
There's
a lot of rich stuff there, in addition to what was needed to work with the
hardware
model.  First auto-pilot from earth to moon and back with primitive
hardware and
software!  The listing images your created are a great archeology dig.  Now
we
need to translate the hieroglyphs to understand the culture that created
this.

Gary Young
proudindiv

**Comment by CrazyPython** [comment]
Too many email sigs.

**Comment by rburkey2005** [comment]
Thank you, and all my trusty minions thank you (I assume). :-)

In return, it's nice to see some people interested enough once again to 
spend their time working on it.  It certainly makes me feel more 
enthusiastic about it than I have in a while.

-- Ron

**Comment by indy91** [comment]
@rburkey2005 Well if you need encouragement, we over at NASSP have been using your amazing work for years and are still working on landing it on the moon. We are very grateful we have the possibility to use the actual AGC code for our simulation. It's an immense challenge to make it work, but always very rewarding. I'm still hoping that one day Skylark and Luminary 1E become available.

**Comment by rburkey2005** [comment]
Unfortunately, nobody has ever given me the slightest hint of where 
Skylark may be found.  Now as far as Luminary 1E is concerned ... I 
won't promise you anything, but I will say that getting my hands on it 
has been something that is near the top of my thoughts the last few 
days, and I'm in the midst of making one of my periodic attempts to 
advance things in that direction.  But only time will tell.

-- Ron

**Comment by chrislgarry** [comment]
@rburkey2005 thanks for digging into that for us. By chance you happened to be in contact with exactly the right person to ask. @wopian according to Hugh's response, any spacing with three consecutive blank lines or less that isn't a page break, let's make sure it conforms to what Hugh mentioned: double spaces seperate logical groups of assembly commands that together perform a specific function, and triple spaces separate these functional groups. Anything not following that heuristic should be suspect and we should correct it according to the heuristic (and apparently notify Hugh as well :))
