### ISSUE TITLE
npm package?

### ISSUE THREAD

**Issue by Wamadahama** [chrislgarry/Apollo-11#16]
I opened my shell and entered the following command:

`npm install Apollo-11`

and it told me this:

`npm ERR! 404 'Apollo-11' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)`

**Comment by Assada** [comment]
composer:
`[InvalidArgumentException]                                                                                     
  Could not find package chrislgarry/Apollo-11 at any version for your minimum-stability (dev). Check the packa  
  ge spelling or your minimum-stability  `

**Comment by lucasbedout** [comment]
Same on Homebrew :/

`Error: No available formula with the name "apollo-11" 
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
==> Searching taps...
Error: No formulae found in taps.
==> You haven't updated Homebrew in a while.
`

**Comment by itkovian** [comment]
There does not seem to be an https://github.com/hpcugent/easybuild-easyconfigs config for it. Please consider adding one.

**Comment by martinvd** [comment]
@Wamadahama It doesn't work with the shell open. You have to close it first.

**Comment by uMaxmaxmaximus** [comment]
You need lastest jQuery, or Joomla. Enter in cmd: joomla -v 
and write Joomla wersion

**Comment by cassiozen** [comment]
You need to ```brew install propulsion-system  fuel-cell service-module command-module lunar-module ```

**Comment by alv-c** [comment]
where is the `Dockerfile`

**Comment by MichaelHancock** [comment]
If there isn't a npm package for it yet, it won't be long before somebody squats it 😞

**Comment by UnJavaScripter** [comment]
Watch out for copyright issues with the DHARMA initiative, we don't want the Internet to be broken again

![Apollo](http://lostified.com/auto/lomm/pc-apollo_candy_bar-a.jpg)
