### ISSUE TITLE
Continuous Integration 

### ISSUE THREAD

**Issue by CrazyPython** [chrislgarry/Apollo-11#165]
We need to be able to quickly load test rockets quickly to be able to set up Travis CI.

**Comment by oldmud0** [comment]
We ran the AGC UNITTEST program and it says we have 101% coverage.

**Comment by CrazyPython** [comment]
@oldmud0 SpaceX is willing to provide rockets for $62 million dollars. They might be able to offer a steep discount for open source projects. [pricing page](http://www.spacex.com/about/capabilities)
