### ISSUE TITLE
Re-write in C or Rust

### ISSUE THREAD

**Issue by radicalachraf** [chrislgarry/Apollo-11#17]
I would like to propose a complete rewrite of the core  systems in C or Rust for the sake of it .

**Comment by funny-falcon** [comment]
No, only Golang can deliver Neil Armstrong to the moon.
Probably, Ruby also could if rubinius will be finished.

**Comment by acoye** [comment]
Only Swift would deliver the "safety" required for manned space flight :)

**Comment by driusan** [comment]
Despite the improvements in the garbage collector lately, Go is still a garbage collected language and not really suitable for a realtime system.

I vote for Rust.

**Comment by nabijaczleweli** [comment]
Go is garbage

**Comment by www2000** [comment]
My chois for this is C or c++ for the backend and python3 for the GUI.
Besite this we can add a sub system for starmap using star database from Celestia and opencv.

**Comment by yeukhon** [comment]
@nabijaczleweli  no need to troll. gtfo

**Comment by nabijaczleweli** [comment]
The only troll here is your face

**Comment by dom96** [comment]
I vote for Nim, instead of dealing with Rust's ownership system use Nim's easy-to-use real-time GC ;)

**Comment by yeukhon** [comment]
@chrislgarry  I vote for banning @nabijaczleweli from ever commenting here again. Little bit of fun turns into unnecessary disrespect.

**Comment by nabijaczleweli** [comment]
I have never flamed unprovoked. Only roastage was committed upon provocation (especially telling me to "gtfo" [sic])

**Comment by yeukhon** [comment]
@nabijaczleweli  your tune is disrespecting. So yes, I will tell you to get the f out.

**Comment by nabijaczleweli** [comment]
\*sigh\* <insert upwards pointing arrow labeled "hypocrite" here>

**Comment by sebastianiag** [comment]
I want to learn Nim so I second the Nim proposal.

**Comment by avesus** [comment]
Hey, let's rewrite this in JavaScript using Node.js and React!

**Comment by oldmud0** [comment]
Screw it, we'll rewrite it in Z80 assembly for the TI-84 calculators.
