### ISSUE TITLE
Comanche055/P11.agc needs commit 944dfb9 from rburkey2005/virtualagc

### ISSUE THREAD

**Issue by proudindiv** [chrislgarry/Apollo-11#171]
Comanche055/P11.agc needs commit 944dfb9 from rburkey2005/virtualagc for yaYUL to assemble Comanche055:  https://github.com/rburkey2005/virtualagc/commit/944dfb97d814c58e17d18d2920f2d65d01101112
The original commit in virtualagc was "jim.lawton committed on May 7, 2011: Fix indentation to use tabs."

This would fix the problems with Comanche055 that I mentioned in PR #170.
The problem was spaces used instead of just tabs when there is no label.  

I don't know how you would like to handle changes from virtualagc.

**Comment by oldmud0** [comment]
I'm going to make a PR for changes that might need to be pulled from the VirtualAGC repo.

**Comment by chrislgarry** [comment]
@proudindiv I have merged these changes in from @oldmud0.
