### ISSUE TITLE
Re-write this in Python

### ISSUE THREAD

**Issue by yeukhon** [chrislgarry/Apollo-11#19]
Because Python is good!

**Comment by nabijaczleweli** [comment]
Python sucks

**Comment by gunner05** [comment]
I need this! I can't understand a single line of Assembly without constantly looking up what it means! haha!

**Comment by yeukhon** [comment]
@nabijaczleweli  very mature of you!

**Comment by nabijaczleweli** [comment]
Almost as if this issue and you were a joke

**Comment by cspgx1996** [comment]
Implying this is a serious discussion, this repo only holds code for the Rocket and all of the properties that define how it would work. Rewriting(converting) this is pointless, unless there is an environment that holds the properties of aerodynamics, the atmosphere, ect. Actual rocket/atmospheric/physics science.
