### ISSUE TITLE
Proof AGC_BLOCK_TWO_SELF-CHECK

### ISSUE THREAD

**Issue by wopian** [chrislgarry/Apollo-11#190]
Proof read transcribed code of [AGC_BLOCK_TWO_SELF-CHECK](//github.com/chrislgarry/Apollo-11/blob/master/Comanche055/AGC_BLOCK_TWO_SELF-CHECK.agc) against scans

Lines: 514
Page: 1394—1403

Reduced quality scans can be found [here][1]

[1]://ibiblio.org/apollo/ScansForConversion/Comanche055

**Comment by alhazmy13** [comment]
I'll start working on this
