### ISSUE TITLE
Proof DOWN-TELEMETRY_PROGRAM

### ISSUE THREAD

**Issue by wopian** [chrislgarry/Apollo-11#201]
Proof read transcribed code of [DOWN-TELEMETRY_PROGRAM](//github.com/chrislgarry/Apollo-11/blob/master/Comanche055/DOWN-TELEMETRY_PROGRAM.agc) against scans

Lines: 458
Page: 1093—1102

Reduced quality scans can be found [here][1]

[1]://ibiblio.org/apollo/ScansForConversion/Comanche055

**Comment by dwiyatci** [comment]
I'm taking this one. 🙇🏻
