### ISSUE TITLE
Proof ENTRY_LEXICON

### ISSUE THREAD

**Issue by wopian** [chrislgarry/Apollo-11#203]
Proof read transcribed code of [ENTRY_LEXICON](//github.com/chrislgarry/Apollo-11/blob/master/Comanche055/ENTRY_LEXICON.agc) against scans

Lines: 374
Page: 0837—0843

Reduced quality scans can be found [here][1]

[1]://ibiblio.org/apollo/ScansForConversion/Comanche055

**Comment by dwiyatci** [comment]
I'm taking this one. 🙇🏻
