### ISSUE TITLE
Proof EXTENDED_VERBS

### ISSUE THREAD

**Issue by wopian** [chrislgarry/Apollo-11#206]
Proof read transcribed code of [EXTENDED_VERBS](//github.com/chrislgarry/Apollo-11/blob/master/Comanche055/EXTENDED_VERBS.agc) against scans

Lines: 1337
Page: 0236—0267

Reduced quality scans can be found [here][1]

[1]://ibiblio.org/apollo/ScansForConversion/Comanche055

**Comment by dwiyatci** [comment]
I'm taking this one. 🙇🏻
