### ISSUE TITLE
Proof FRESH_START_AND_RESTART

### ISSUE THREAD

**Issue by wopian** [chrislgarry/Apollo-11#208]
Proof read transcribed code of [FRESH_START_AND_RESTART](//github.com/chrislgarry/Apollo-11/blob/master/Comanche055/FRESH_START_AND_RESTART.agc) against scans

Lines: 1475
Page: 0181—0210

Reduced quality scans can be found [here][1]

[1]://ibiblio.org/apollo/ScansForConversion/Comanche055

**Comment by dwiyatci** [comment]
I'm taking this one. 🙇🏻
