### ISSUE TITLE
Proof IMU_MODE_SWITCHING_ROUTINES

### ISSUE THREAD

**Issue by wopian** [chrislgarry/Apollo-11#213]
Proof read transcribed code of [IMU_MODE_SWITCHING_ROUTINES](//github.com/chrislgarry/Apollo-11/blob/master/Comanche055/IMU_MODE_SWITCHING_ROUTINES.agc) against scans

Lines: 1069
Page: 1420—1448

Reduced quality scans can be found [here][1]

[1]://ibiblio.org/apollo/ScansForConversion/Comanche055

**Comment by dwiyatci** [comment]
I'm taking this one. 🙇🏻
