### ISSUE TITLE
Proof INTEGRATION_INITIALIZATION

### ISSUE THREAD

**Issue by wopian** [chrislgarry/Apollo-11#215]
Proof read transcribed code of [INTEGRATION_INITIALIZATION](//github.com/chrislgarry/Apollo-11/blob/master/Comanche055/INTEGRATION_INITIALIZATION.agc) against scans

Lines: 1183
Page: 1309—1333

Reduced quality scans can be found [here][1]

[1]://ibiblio.org/apollo/ScansForConversion/Comanche055

**Comment by DanFoad** [comment]
I'd like to take this on

**Comment by DanFoad** [comment]
PR Created: https://github.com/chrislgarry/Apollo-11/pull/509
