### ISSUE TITLE
Proof JET_SELECTION_LOGIC

### ISSUE THREAD

**Issue by wopian** [chrislgarry/Apollo-11#220]
Proof read transcribed code of [JET_SELECTION_LOGIC](//github.com/chrislgarry/Apollo-11/blob/master/Comanche055/JET_SELECTION_LOGIC.agc) against scans

Lines: 933
Page: 1039—1062

Reduced quality scans can be found [here][1]

[1]://ibiblio.org/apollo/ScansForConversion/Comanche055

**Comment by dwiyatci** [comment]
I'm taking this one. 🙇🏻
