### ISSUE TITLE
Proof LATITUDE_LONGITUDE_SUBROUTINES

### ISSUE THREAD

**Issue by wopian** [chrislgarry/Apollo-11#223]
Proof read transcribed code of [LATITUDE_LONGITUDE_SUBROUTINES](//github.com/chrislgarry/Apollo-11/blob/master/Comanche055/LATITUDE_LONGITUDE_SUBROUTINES.agc) against scans

Lines: 319
Page: 1236—1242

Reduced quality scans can be found [here][1]

[1]://ibiblio.org/apollo/ScansForConversion/Comanche055

**Comment by dwiyatci** [comment]
I'm taking this one. 🙇🏻
