### ISSUE TITLE
Proof MAIN

### ISSUE THREAD

**Issue by wopian** [chrislgarry/Apollo-11#226]
Proof read transcribed code of [MAIN](//github.com/chrislgarry/Apollo-11/blob/master/Comanche055/MAIN.agc) for any errors/page numbering

Lines: 169
Page: N/A

**Comment by dwiyatci** [comment]
@wopian Which are the corresponding scans for this one?

**Comment by oldmud0** [comment]
There are no scans for this file; it is a meta-file. I will close this since there isn't much to proofread here, except maybe the page numbers.

**Comment by wopian** [comment]
@dwiyatci just a general proof reading of the comments/file references

**Comment by chrislgarry** [comment]
This is a header file made by virtualAGC folks to compile the individual source files for their project. The comments near each include statement were just an index for them to know which physical pages the source files corresponded to. 

This was not in the AGC original code, however as an index for the source code, it is valuable. We should rename this file to something like Comanche055_Index.md, format it so its easily readable by a script. If you agree, then just merge in the PR I made to do this https://github.com/chrislgarry/Apollo-11/pull/318. I believe Luminary also has its own main.agc file too.
