### ISSUE TITLE
Proof MEASUREMENT_INCORPORATION

### ISSUE THREAD

**Issue by wopian** [chrislgarry/Apollo-11#227]
Proof read transcribed code of [MEASUREMENT_INCORPORATION](//github.com/chrislgarry/Apollo-11/blob/master/Comanche055/MEASUREMENT_INCORPORATION.agc) against scans

Lines: 504
Page: 1252—1261

Reduced quality scans can be found [here][1]

[1]://ibiblio.org/apollo/ScansForConversion/Comanche055

**Comment by donquxiote** [comment]
hey @wopian if this is still available, I'd like to take it and do the proof reading.

**Comment by wopian** [comment]
@donquxiote it's still available :+1:
