### ISSUE TITLE
Proof ORBITAL_INTEGRATION

### ISSUE THREAD

**Issue by wopian** [chrislgarry/Apollo-11#229]
Proof read transcribed code of [ORBITAL_INTEGRATION](//github.com/chrislgarry/Apollo-11/blob/master/Comanche055/ORBITAL_INTEGRATION.agc) against scans

Lines: 950
Page: 1334—1354

Reduced quality scans can be found [here][1]

[1]://ibiblio.org/apollo/ScansForConversion/Comanche055

**Comment by dwiyatci** [comment]
I'm taking this one. 🙇🏻
