### ISSUE TITLE
Add automated tests and run with CI

### ISSUE THREAD

**Issue by driusan** [chrislgarry/Apollo-11#24]
There doesn't appear to be any tests included with this software. Over time as requirements change there's a risk of catastrophic failure after a couple of versions if there aren't regression tests to catch any minor oversights. The lack of systematic automated testing also makes it more difficult for any of the "rewrite in language x" proposals to be successful.

Since it's hosted on GitHub, I recommend setting up some simple tests to run with Travis.

**Comment by JoaoGFarias** [comment]
Relax, we will never go to the moon again; requirements won't change, sadly.
