### ISSUE TITLE
Proof PHASE_TABLE_MAINTENANCE

### ISSUE THREAD

**Issue by wopian** [chrislgarry/Apollo-11#240]
Proof read transcribed code of [PHASE_TABLE_MAINTENANCE](//github.com/chrislgarry/Apollo-11/blob/master/Comanche055/PHASE_TABLE_MAINTENANCE.agc) against scans

Lines: 407
Page: 1404—1413

Reduced quality scans can be found [here][1]

[1]://ibiblio.org/apollo/ScansForConversion/Comanche055

**Comment by RandomGuyDTB** [comment]
Proofread page 1404, looks good to me but I made a pull request for a possible error in transcription.

**Comment by RandomGuyDTB** [comment]
Proofread 1406, added another pull request for my corrections.

**Comment by dwiyatci** [comment]
@RandomGuyDTB Are you planning to finish this? Or may I take over from pp. 1409-1413? :)

**Comment by RandomGuyDTB** [comment]
Yeah, got sidetracked and forgot about this. Go ahead, maybe when school gets out I'll start helping again. Thanks.
