### ISSUE TITLE
Proof PINBALL_NOUN_TABLES

### ISSUE THREAD

**Issue by wopian** [chrislgarry/Apollo-11#242]
Proof read transcribed code of [PINBALL_NOUN_TABLES](//github.com/chrislgarry/Apollo-11/blob/master/Comanche055/PINBALL_NOUN_TABLES.agc) against scans

Lines: 868
Page: 0268—0284

Reduced quality scans can be found [here][1]

[1]://ibiblio.org/apollo/ScansForConversion/Comanche055

**Comment by dwiyatci** [comment]
I'm taking this one. 🙇🏻
