### ISSUE TITLE
Proof RCS-CSM_DIGITAL_AUTOPILOT

### ISSUE THREAD

**Issue by wopian** [chrislgarry/Apollo-11#249]
Proof read transcribed code of [RCS-CSM_DIGITAL_AUTOPILOT](//github.com/chrislgarry/Apollo-11/blob/master/Comanche055/RCS-CSM_DIGITAL_AUTOPILOT.agc) against scans

Lines: 977
Page: 1002—1024

Reduced quality scans can be found [here][1]

[1]://ibiblio.org/apollo/ScansForConversion/Comanche055

**Comment by dwiyatci** [comment]
I'm taking this one. 🙇🏻
