### ISSUE TITLE
Houston we need a JS link

### ISSUE THREAD

**Issue by thefailtheory** [chrislgarry/Apollo-11#25]
I just ask if it's possible to link those images in a modern approach like in a jsfiddle.net with some javascript
https://imgur.com/a/pcdKy

like what i am asking in this issue https://github.com/chrislgarry/Apollo-11/issues/9#issuecomment-231382253

In do Something fun this way https://github.com/chrislgarry/Apollo-11/issues/8#issuecomment-231378578

**Comment by thefailtheory** [comment]
Here how it's going

https://jsfiddle.net/2h52du54/2/

THX :zap:

**Comment by SkiftCreative** [comment]
boom http://svtsim.com/moonjs/agc.html

**Comment by thefailtheory** [comment]
VERB 00 enter
NOUN 60 enter

https://imgur.com/mVAahV2

**Comment by thefailtheory** [comment]
![mvaahv2](https://cloud.githubusercontent.com/assets/1375686/16697998/7ea8f8c0-454c-11e6-8052-158311cf7e2f.gif)

**Comment by thefailtheory** [comment]
i don't see the link between
verb 00 enter
noun 60 enter

then the [key moment](http://apollo13.spacelog.org/02:07:52:58/02:07:56:10/#log-line-201178)
