### ISSUE TITLE
Proof RESTARTS_ROUTINE

### ISSUE THREAD

**Issue by wopian** [chrislgarry/Apollo-11#251]
Proof read transcribed code of [RESTARTS_ROUTINE](//github.com/chrislgarry/Apollo-11/blob/master/Comanche055/RESTARTS_ROUTINE.agc) against scans

Lines: 336
Page: 1414—1419

Reduced quality scans can be found [here][1]

[1]://ibiblio.org/apollo/ScansForConversion/Comanche055

**Comment by keller0** [comment]
#327
