### ISSUE TITLE
Proof STAR_TABLES

### ISSUE THREAD

**Issue by wopian** [chrislgarry/Apollo-11#259]
Proof read transcribed code of [STAR_TABLES](//github.com/chrislgarry/Apollo-11/blob/master/Comanche055/STAR_TABLES.agc) against scans

Lines: 194
Page: 1389—1393

Reduced quality scans can be found [here][1]

[1]://ibiblio.org/apollo/ScansForConversion/Comanche055

**Comment by Feliix42** [comment]
I just proof read this section. As far as I can tell, the transcript is correct.

**Comment by wopian** [comment]
Thanks 👌
