### ISSUE TITLE
Proof SXTMARK

### ISSUE THREAD

**Issue by wopian** [chrislgarry/Apollo-11#260]
Proof read transcribed code of [SXTMARK](//github.com/chrislgarry/Apollo-11/blob/master/Comanche055/SXTMARK.agc) against scans

Lines: 703
Page: 0222—0235

Reduced quality scans can be found [here][1]

[1]://ibiblio.org/apollo/ScansForConversion/Comanche055

**Comment by dwiyatci** [comment]
I'm taking this one. 🙇🏻
