### ISSUE TITLE
Proof TIME_OF_FREE_FALL

### ISSUE THREAD

**Issue by wopian** [chrislgarry/Apollo-11#264]
Proof read transcribed code of [TIME_OF_FREE_FALL](//github.com/chrislgarry/Apollo-11/blob/master/Comanche055/TIME_OF_FREE_FALL.agc) against scans

Lines: 711
Page: 1373—1388

Reduced quality scans can be found [here][1]

[1]://ibiblio.org/apollo/ScansForConversion/Comanche055

**Comment by dwiyatci** [comment]
I'm taking this one. 🙇🏻
