### ISSUE TITLE
Proof TPI_SEARCH

### ISSUE THREAD

**Issue by wopian** [chrislgarry/Apollo-11#265]
Proof read transcribed code of [TPI_SEARCH](//github.com/chrislgarry/Apollo-11/blob/master/Comanche055/TPI_SEARCH.agc) against scans

Lines: 558
Page: 0551—0561

Reduced quality scans can be found [here][1]

[1]://ibiblio.org/apollo/ScansForConversion/Comanche055

**Comment by dwiyatci** [comment]
I'm taking this one. 🙇🏻
