### ISSUE TITLE
Proof TVCDAPS

### ISSUE THREAD

**Issue by wopian** [chrislgarry/Apollo-11#266]
Proof read transcribed code of [TVCDAPS](//github.com/chrislgarry/Apollo-11/blob/master/Comanche055/TVCDAPS.agc) against scans

Lines: 782
Page: 0961—0978

Reduced quality scans can be found [here][1]

[1]://ibiblio.org/apollo/ScansForConversion/Comanche055

**Comment by dwiyatci** [comment]
I'm taking this one. 🙇🏻
