### ISSUE TITLE
Proof TVCEXECUTIVE

### ISSUE THREAD

**Issue by wopian** [chrislgarry/Apollo-11#267]
Proof read transcribed code of [TVCEXECUTIVE](//github.com/chrislgarry/Apollo-11/blob/master/Comanche055/TVCEXECUTIVE.agc) against scans

Lines: 274
Page: 0945—0950

Reduced quality scans can be found [here][1]

[1]://ibiblio.org/apollo/ScansForConversion/Comanche055

**Comment by chrislgarry** [comment]
Thanks @Gaboso
