### ISSUE TITLE
Proof TVCMASSPROP

### ISSUE THREAD

**Issue by wopian** [chrislgarry/Apollo-11#269]
Proof read transcribed code of [TVCMASSPROP](//github.com/chrislgarry/Apollo-11/blob/master/Comanche055/TVCMASSPROP.agc) against scans

Lines: 240
Page: 0951—0955

Reduced quality scans can be found [here][1]

[1]://ibiblio.org/apollo/ScansForConversion/Comanche055

**Comment by Inari-Whitebear** [comment]
So I was going to help out with this, but I'm really confused on how this works. It says tab indentation and tab-size 8, but when I do that, stuff doesn't line up..

Like here: https://github.com/chrislgarry/Apollo-11/blob/master/Comanche055/TVCMASSPROP.agc#L36

In the file http://www.ibiblio.org/apollo/ScansForConversion/Comanche055/0951.jpg the ":" two lines above that lines up with the space after "OPERATES", but it doesn't if I use tab-size of 8?

**Comment by wopian** [comment]
The 8 tab width is for the alignment of the assembly code. The comments are (annoyingly) rarely correctly aligned by tabs.

For example, it needs 5 spaces instead:

![](https://i.imgur.com/UiMSbIr.png)

**Comment by Inari-Whitebear** [comment]
Ah, I see ^^ Thanks

**Comment by dwiyatci** [comment]
@Inari-Whitebear Have you been working on this? If not, may I take over this one? ^^

**Comment by Inari-Whitebear** [comment]
I had a bit, but found the code part formatting confusing to proofread/adjust, and didn't have as much time for it. So feel free to do it.
