### ISSUE TITLE
Proof UPDATE_PROGRAM

### ISSUE THREAD

**Issue by wopian** [chrislgarry/Apollo-11#273]
Proof read transcribed code of [UPDATE_PROGRAM](//github.com/chrislgarry/Apollo-11/blob/master/Comanche055/UPDATE_PROGRAM.agc) against scans

Lines: 555
Page: 1497—1507

Reduced quality scans can be found [here][1]

[1]://ibiblio.org/apollo/ScansForConversion/Comanche055

**Comment by keller0** [comment]
![p2](https://user-images.githubusercontent.com/19371712/37963935-648b34b4-31f2-11e8-961f-179467c2b477.png)
It seems like a print error,is that right?
I changed that to: 
![p4](https://user-images.githubusercontent.com/19371712/37965181-cd176580-31f6-11e8-8587-b2083f39bf40.png)
Like [code in Luminary099/UPDATE_PROGRAM.agc](https://github.com/chrislgarry/Apollo-11/blob/master/Luminary099/UPDATE_PROGRAM.agc)
![p3](https://user-images.githubusercontent.com/19371712/37964764-331ae980-31f5-11e8-98a0-aee4ea6014a9.png)
