### ISSUE TITLE
Won't build on Win 10

### ISSUE THREAD

**Issue by joshmgrant** [chrislgarry/Apollo-11#28]
I tried cloning the source and building on Windows 10 but I couldn't get it to work. Am I missing any dependencies or utilities?

**Comment by x8BitRain** [comment]
This is a really great circlejerk repository

**Comment by chinese-soup** [comment]
i hpe bitrain dies in his sleep tonighjt

**Comment by x8BitRain** [comment]
i hope u drown in ur soup tonighgt

**Comment by www2000** [comment]
This is not a x86, x86_64 or assembly language.
Try a VM that support Apollo Guidance Computer hardware.
Or wait for the C/C++ port

**Comment by darcy** [comment]
![works-on-my-machine-starburst](https://cloud.githubusercontent.com/assets/6201/16708817/4b9d6e74-45c5-11e6-980c-465f24f61766.gif)

**Comment by OsamaShabrez** [comment]
Works perfectly fine on macOS Sierra beta

**Comment by cirosantilli** [comment]
superset: https://github.com/chrislgarry/Apollo-11/issues/8
