### ISSUE TITLE
A flat badge for NASA

### ISSUE THREAD

**Issue by aleen42** [chrislgarry/Apollo-11#286]
Here is [a repository](https://github.com/aleen42/badges) for making badges more acceptable in documenting, and I hope that the flat badge can be used in such an awesome project. 

[![nasa](https://rawgit.com/aleen42/badges/master/src/nasa.svg)](https://rawgit.com/aleen42/badges/master/src/nasa.svg)

**Comment by wopian** [comment]
@chrislgarry thoughts? NASA badge has the potential of the project being mistaken as an official NASA project - although it's on code.nasa.gov as a "NASA Open Source Software Project" and you're an intern there, so I have no idea where this project stands ¯\_(ツ)_/¯

@aleen42 the logo on the badge is horizontally squished:
![](http://i.imgur.com/O2pX6D6.png)

**Comment by chrislgarry** [comment]
@aleen42 it looks great! @wopian this is on code.nasa.gov? Awesome! "NASA content used in a factual manner that does not imply endorsement may be used without needing explicit permission" :
https://www.nasa.gov/multimedia/guidelines/index.html. It's a little gray. Let's pull it in for now and I'll ask them. I don't think it'll be an issue but if it is, we just remove the logo.

**Comment by chrislgarry** [comment]
Let's unsquish it though. @aleen42 make sure you're using media material directly from NASA. They have high quality svg available. I can't find the logo kit but I found this: https://pmm.nasa.gov/science-team/resources/nasa-logo

**Comment by chrislgarry** [comment]
@wopian thanks for the help.

**Comment by aleen42** [comment]
@wopian @chrislgarry  Check the newest one, and it has been unsquished.

**Comment by aleen42** [comment]
Here is a large picture for checking details. ![2017-03-26_224136](https://cloud.githubusercontent.com/assets/9573300/24332223/725e5654-1275-11e7-9c83-c2383e2daef8.jpg)

**Comment by chrislgarry** [comment]
@aleen42 Added! Is there a way to add it to the repo description as well? If you have suggestions about where to add the badge let me know, otherwise this can be closed. Thank you!

**Comment by aleen42** [comment]
@chrislgarry How about adding it in a single line following the title?


Apollo-11
=========

[![nasa](https://rawgit.com/aleen42/badges/master/src/nasa.svg)]()

*Available in: [English][EN], [简体中文][ZH_CN], [正體中文][ZH_TW].*

**Comment by amin007** [comment]
Good. Cdn?

**Comment by aleen42** [comment]
@amin007, badges are not stored on CDN

**Comment by wopian** [comment]
Ah yeah, should've been using the production URL instead of the development URL of RawGit which uses StackPath's CDN.

**Comment by aleen42** [comment]
@wopian great.
