### ISSUE TITLE
Clicking on NASA badge redirects to GitHub 404 page

### ISSUE THREAD

**Issue by chrislgarry** [chrislgarry/Apollo-11#287]
I'm thinking either remove the link or have it link to code.nasa.gov? However, that may be a tad redundant. Perhaps a link to a NASA page for the Apollo missions? Lets discuss. @wopian @aleen42 @oldmud0

**Comment by wopian** [comment]
Either making it a non-link image or linking to [this nasa.gov](https://www.nasa.gov/mission_pages/apollo/missions/apollo11.html) page would be 👍

**Comment by chrislgarry** [comment]
I think https://www.nasa.gov/mission_pages/apollo/missions/apollo11.html is good. Lets see what others have to say.

**Comment by aleen42** [comment]
@wopian @chrislgarry I also think that it's better to redirect to the original project site: https://www.nasa.gov/mission_pages/apollo/missions/apollo11.html.

**Comment by oldmud0** [comment]
Yeah I was intending to report that but forgot to :/

Hmm, I originally wanted to link to the code.nasa.gov site but I see your line of reasoning since it'll just link back here. However you can already look up info about the Apollo 11 mission in Wikipedia or elsewhere, so maybe it would be the best idea to link to code.nasa.gov since it proves that NASA really does "endorse" the project and that it is authentic.

**Comment by wopian** [comment]
General consensus was in support for the Apollo 11 mission page 👍

**Comment by oldmud0** [comment]
But, what about my argument for code.nasa.gov?

**Comment by chrislgarry** [comment]
I agree it does give us credibility, but code.nasa.gov will just link users
back to this repo. So for reputation it is great but in terms of usefulness
for users it's not helpful I think. The readme is for understanding the
project, so the apollo missions page makes sense.

On Tue, Apr 11, 2017 at 7:53 oldmud0 <notifications@github.com> wrote:

But, what about my argument for code.nasa.gov?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/chrislgarry/Apollo-11/issues/287#issuecomment-293101818>,
or mute the thread
