### ISSUE TITLE
remove hurtful comments

### ISSUE THREAD

**Issue by WindedCone** [chrislgarry/Apollo-11#29]
please remove all references to "burning babies" in BURN_BABY_BURN--MASTER_IGNITION_ROUTINE.s , it is hurtful and I do not think it is good for our image

**Comment by nabijaczleweli** [comment]
laff

**Comment by Nashenas88** [comment]
@WindedCone you should read it as, "Burn, baby! Burn!" In this context, baby doesn't mean an actual child. See https://en.wikipedia.org/wiki/Burn_Baby_Burn

**Comment by CrazyPython** [comment]
There's also several easter eggs in the code.

**Comment by x8BitRain** [comment]
nice meme

**Comment by lbotinelly** [comment]
That piece of legacy code was written before the DPC (Dawn of Politically Correctedness) and grandfathered in. I suggest we add both the `dealwithit` and `wontfix` label.

**Comment by sebastianiag** [comment]
Someone just close this "issue".

**Comment by WindedCone** [comment]
i cant beliv what im c ing, laff, nice MEME( a racicst code word 4 BlaCK HATE) thes is a very big issue annf i wil not stpo untill it is elminted !!
am assamed!!! at all of you!!!

**Comment by fat-tire** [comment]
All I have to say is [WHOCARES](https://github.com/chrislgarry/Apollo-11/search?utf8=%E2%9C%93&q=WHOCARES)

**Comment by DoubleCouponDay** [comment]
muh triggered feelings

**Comment by Austinthemighty** [comment]
@WindedCone Just get of git hub if you are going to try to be politically correct at things, no one here is going to change history, just for one person who felt offended!

**Comment by Monster-geek** [comment]
@WindedCone you don't understand the real meaning of "BURN_BABY_BURN" in MASTER_IGNITION_ROUTINE.s ... It's ignition routine. "Burn" mean the ignition of rocket engine and so the rocket engine are called Baby like you can call your girlfriend/boyfriend babe or baby. There is absolutly no actual babies burned joke in this code. Stop see the evil everywhere.
Now I don't ask you to make any appologies but just closing this "issue" by yourself will be good.

**Comment by egorikem** [comment]
Welp, some sort of clever body is making up things (which, by the way, don't seem to be any realistic, referring to the source code and/or situation). And, of course, spells like a complete retard. Is that supposed to by funny? Amusing? Cool? Why this "issue" is ever there?

**Comment by CrazyPython** [comment]
@egorikem it's supposed to be sarcastic, and the misspellings are on purpose.

**Comment by egorikem** [comment]
@CrazyPython And I am supposed to be the president of US then. No, it does not appear to be sarcastic, it appears to be relatively retarded.

**Comment by Pranoy1c** [comment]
this is code as it was. if you have a problem with it, just don't look at the code. there is no reason for them to come in and change this code to something which it wasn't. stop being offended at every single thing and take a chill pill and enjoy the joke.

**Comment by mokalovesoulmate** [comment]
I am surprised that there is someone offended on this piece of code by today. Actually, I am wishing more piece of codes like this. Lol.

Anyway I agree with @Monster-geek.

**Comment by WindedCone** [comment]
w,.... w,,,, w,,,, wow,,,,,... i cnt .......... y u ppl not sem to car about the ramifykations of the wirds,,,, y u ppl ned to bee so mean..... i,,,,, i..... I,,,,,, u r bad, i ned. a break of..... water///..../,.

**Comment by CrazyPython** [comment]
@WindedCone Why can't you spell at all? Why so many commas and periods? Can you type?

**Comment by egorikem** [comment]
@CrazyPython Oh, so after all you do obliquely agree with my point?

**Comment by CrazyPython** [comment]
@Georgii Savatkov According to /r/programmerhumor it's funny
