### ISSUE TITLE
Spaceship won't power on.

### ISSUE THREAD

**Issue by Dimmerworld** [chrislgarry/Apollo-11#295]
Trying to get to moon for a business meeting and the code is throwing the error "322 - Mainframe missing", any idea?

**Comment by Dimmerworld** [comment]
Someone already did my joke :(

**Comment by lgeurts** [comment]
Still funny :).

**Comment by chrislgarry** [comment]
@Dimmerworld Apollo 11 has been deprecated. Sorry for the inconvenience.

**Comment by amin007** [comment]
Meeting at where?
