### ISSUE TITLE
Make translate in malay language?

### ISSUE THREAD

**Issue by amin007** [chrislgarry/Apollo-11#305]

**Comment by oldmud0** [comment]
Sorry, I don't know anyone who knows Malay.

**Comment by amin007** [comment]
ok. :(

**Comment by chrislgarry** [comment]
@amin007 If you know somebody who can translate, we would be very happy. Please recommend them! Thank you.

**Comment by johnhigginsavila** [comment]
Does any one already translate this to Filipino language?

**Comment by amin007** [comment]
@chrislgarry I can offer myself if no one else is interested

**Comment by danialhx** [comment]
Hi, still need a Malay translator?

**Comment by chrislgarry** [comment]
@danialhx sure! Thatd be great :)

**Comment by wasquared9** [comment]
Umm, I don't know if anyone knows, but google translate does Malay. you might be able to just copy and paste to it.

**Comment by YasPHP** [comment]
@johnhigginsavila not yet, can you translate it to Filipino?

**Comment by feiduan1211** [comment]
Why don't you use Google Translate?-.-

**Comment by elsandosgrande** [comment]
@wasquared9 @feiduan1211 Google Translate and Bing Translator are not adequate for anything more than being interactive dictionaries at the moment. Come back with this suggestion in a few decades and the situation *might* be different.
