### ISSUE TITLE
Javascript AGC assembly code simulator

### ISSUE THREAD

**Issue by thefailtheory** [chrislgarry/Apollo-11#31]
It seems that there is a simulator available, i have just tested it locally, perhaps it could do the job

https://github.com/Schweigi/assembler-simulator

if someone can start to code it it will be really appreciated

**Comment by thefailtheory** [comment]
this doc is clear on the subject, i should find others to start with the registers first
http://tcf.pages.tcnj.edu/files/2013/12/Apollo-Guidance-Computer-2009.pdf

we should start with this piece of code to define registers

`// Allowed registers: A, B, C, D, SP
            var parseRegister = function (input) {
                input = input.toUpperCase();

                if (input === 'A') {
                    return 0;
                } else if (input === 'B') {
                    return 1;
                } else if (input === 'C') {
                    return 2;
                } else if (input === 'D') {
                    return 3;
                } else if (input === 'SP') {
                    return 4;
                } else {
                    return undefined;
                }
};`

**Comment by thefailtheory** [comment]
btw, i have found in this page the instruction set [apollo/assembly_language_manual](http://www.ibiblio.org/apollo/assembly_language_manual.html)

**Comment by ConnectedReasoning** [comment]
runs pretty slow. About  2 seconds per letter to write hello world
