### ISSUE TITLE
Add links to original scans in CONTRIBUTING.md

### ISSUE THREAD

**Issue by chrislgarry** [chrislgarry/Apollo-11#320]
We need to add links to the original scans in contributing.md and mention that any commits should be checked against those scans before making a PR. Example of confused contributor: https://github.com/chrislgarry/Apollo-11/pull/319

**Comment by ameerthehacker** [comment]
@chrislgarry if you dont mind shall i take this issue and if so it would be of hreat help if you can tell what are the scans to be linked

**Comment by chrislgarry** [comment]
Sure that’d be great! In the README.md, you will see two links in the
description for all of the images for Comanche and Luminary pages. We just
want to include those links in CONTRIBUTING.md with a note saying before
you make a PR, please make sure your changes are consistent with the
original AGC printouts. Thanks!

**Comment by ameerthehacker** [comment]
Thanks @chrislgarry i will start working on it right away

**Comment by oldmud0** [comment]
Closed by 87610c5e527b977541b73e95e7cb9e659d04bdeb
