### ISSUE TITLE
Loss of telemetry, SCE to AUX (Version 12.X)

### ISSUE THREAD

**Issue by rtphokie** [chrislgarry/Apollo-11#33]
Found in production with version 12.X, Service Module (SM) fuel cells.  Customer support (EECOM) suggested workaround of _SCE to Aux_ resolved the issue, enabling systems to function normally under low voltage.

Recovery from such situations should be automated as a [steely-eye'd missile man](https://en.wikipedia.org/wiki/John_Aaron) man not always be available on the helpline..

**Comment by lbotinelly** [comment]
Temporary fix / Plan B: Implement steely-eye'd missile man breeding program, have at least one assigned per launch.
