### ISSUE TITLE
Potential unit mismatch

### ISSUE THREAD

**Issue by osresearch** [chrislgarry/Apollo-11#35]
The internal computation is carried out in meters/kilos/newtons, but the input and display routines are all in feet/pounds/pounds.  This could lead to a [Mars Climate Orbiter type failure](https://en.wikipedia.org/wiki/Mars_Climate_Orbiter#Cause_of_failure) if the conversion function is omitted or applied in the incorrect direction.  Ideally the astronauts would be trained to use the Metric system, which might be less error prone than redoing all calculations with antiquated units.

**Comment by Sword-Smith** [comment]
SI units are only for French people and for socialists!

Oh! I am repeating myself. Sorry.

**Comment by posto** [comment]
@Sword-Smith : sure it is, http://www.nerdylorrin.net/jerry/postages/MapOfCountriesNotMetric-800px.jpg
