### ISSUE TITLE
Can we run this in a container? 

### ISSUE THREAD

**Issue by svengt** [chrislgarry/Apollo-11#39]
🐳

**Comment by santec** [comment]
Yes:

docker run -d apollo-11:latest

**Comment by peuamorim** [comment]
Error:

Unable to find image 'apollo-11:latest' locally
Pulling repository docker.io/library/apollo-11
docker: Error: image library/apollo-11 not found.
See 'docker run --help'.

**Comment by venriq** [comment]
Sarcasm?

**Comment by cspgx1996** [comment]
Unless there's an amazing open source program that simulates rockets(written in assembly) blasting off; No...t yet

**Comment by aajahid** [comment]
There is amazing program that simulates rockets - 
http://ibiblio.org/apollo/index.html

Found the domain from author email address in on of the source comment

**Comment by howditgetburned** [comment]
Yes but your computer will fly away from you and into space, so run it wisely.

**Comment by aajahid** [comment]
Hmm thats a problem, may be we can port SpaceX landing module - so we can get back our computer back intact? 
Btw did SpaceX released their stable build or is it still unstable?

**Comment by howditgetburned** [comment]
The current most well documented workaround is to put a sack of bricks on your computer before you attempt to use the program. You can also try turning it off and turning it back on again

**Comment by cirosantilli** [comment]
possible duplicate of: https://github.com/chrislgarry/Apollo-11/issues/8

**Comment by santec** [comment]
More seriously: Apollo-11 computer did not run a modern version of Linux, so no, you cannot run this program in a container.
