### ISSUE TITLE
Adding a video with Margaret Hamilton to README?

### ISSUE THREAD

**Issue by fhajji** [chrislgarry/Apollo-11#407]
Please consider adding a link to this very instructive talk by Margaret Hamilton
to the README:

https://www.youtube.com/watch?v=ZbVOF0Uk5lU

**Comment by wopian** [comment]
You can add her talk (and others) to the Wiki page!

https://github.com/chrislgarry/Apollo-11/wiki/Online-resources-related-to-the-AGC
