### ISSUE TITLE
How about a code of conduct?

### ISSUE THREAD

**Issue by CoralineAda** [chrislgarry/Apollo-11#411]
https://www.contributor-covenant.org/version/1/4/code-of-conduct

:)

**Comment by jerdog** [comment]
Any project, especially one that has a public call for contributions like this one, needs a Code of Conduct. Great suggestion.

**Comment by socram8888** [comment]
They literally went to the moon using this code without having one. I really fail to see why this __needs__ it.

**Comment by crispycookies** [comment]
I dont think any repository needs a code of conduct... 
If you feel mistreated, leave the repo... 
This is no Kindergarden where some supervisor punishes you for bad behaviour.
Only merits count... Not behaviour.

**Comment by vizakenjack** [comment]
How about a code of conduct in your project? https://github.com/CoralineAda/lftm/issues/2

**Comment by tannisroot** [comment]
Do you actually **_want_** people to hate you?

**Comment by spiritworldcorp** [comment]
How about coming up with a real issue?

**Comment by Valmar33** [comment]
Ah... it's the infamous Coraline, the woman who's been pushing their CoC down the throats of innumerable projects, and who goes on insane tirades on Twitter.

**Comment by honestabe10** [comment]
Dumb idea

**Comment by cortical-iv** [comment]
She literally put a smiley face

**Comment by wopian** [comment]
Please keep discussion in this repository civil.

**Comment by cthpw103** [comment]
i personally agree, apollo 11 NEEDS a code of conduct.

**Comment by v1ruben** [comment]
how about no

**Comment by rlperez** [comment]
No and quit going around trying to destroy code base communities with your nonsense.

**Comment by aljex** [comment]
I think a good code of conduct is one where you don't do things like submit codes of conduct.

**Comment by LethalManBoob** [comment]
No and people like you who have activist in your name should be banned

**Comment by ShadowHatesYou** [comment]
https://geekfeminism.wikia.org/wiki/OpalGate_incident

https://github.com/opal/opal/issues/941

**Comment by dm17** [comment]
1) We didn't go to the moon - or have a live stream from there in '69 - and then "destroy all of the technology required to go"
2) Your activism is inherently authoritarian - the opposite of what you claim.

**Comment by SpawnOrion** [comment]
No. The problem is that people such as Coraline, who brag about being activists in their bio, frequently use these codes of conduct to kudgel everyone not like them into submission while acting in reprehensible ways without being held to account for their own bigotry.
Submitting to Coraline's polite demand, and let's be honest, her history shows that this will soon turn into a demand, gives her the power and appeals to her base need for authoritarian rule over everyone not like her. The road may not be easy, regardless of which path you take.
Might as well take the honorable path and be damned than to be her thrall.

**Comment by oldmud0** [comment]
All right, all right, I think there is enough opposition to make the point. Locking as a precaution, to prevent this thread from, er, going too far.
