### ISSUE TITLE
亲测可用！我现在在月球，生命体征平稳！

### ISSUE THREAD

**Issue by JackJoeHome** [chrislgarry/Apollo-11#446]

**Comment by AyagawaSeirin** [comment]
记得拍张地球的照片，微信的启动图该换换了

**Comment by JackJoeHome** [comment]
> 记得拍张地球的照片，微信的启动图该换换了

![1](https://user-images.githubusercontent.com/12382626/61520963-d682c000-aa41-11e9-8ac8-d2d593dbe339.png)
地球很美

**Comment by Yoefs** [comment]
抖你M的机灵呢，丢人

**Comment by cannotbeblank** [comment]
nmsl

**Comment by cannotbeblank** [comment]
> 
> 
> _No description provided._

nmsl

**Comment by curse-zhina** [comment]
你妈死了
