### ISSUE TITLE
长大了我要当太空员，老师可高兴了，给我看最爱的汇编源代码。

### ISSUE THREAD

**Issue by Albelt** [chrislgarry/Apollo-11#448]
![image](https://user-images.githubusercontent.com/35684393/61520329-89521e80-aa40-11e9-9c8f-717c4a8f3314.png)

**Comment by qq1037861239** [comment]
图没发绿，差评！

**Comment by Albelt** [comment]
偶尔皮一下很开心:)

**Comment by wuyugege** [comment]
傻屌
