### ISSUE TITLE
招聘前端，中级，简历投送346916672@qq.com

### ISSUE THREAD

**Issue by JackCapillary** [chrislgarry/Apollo-11#454]

**Comment by JerryBaojin** [comment]
what's your problem?

**Comment by AyagawaSeirin** [comment]
what's your problem?

**Comment by qq1037861239** [comment]
what's your problem?

**Comment by qq1037861239** [comment]
what's your problem?

**Comment by qq1037861239** [comment]
本人精通C、C++、Java、C#、VB、HTML、Delphi、JavaScript、PHP等语言的拼写,熟练掌握PhotoShop、Illustrator CS、CorelDraw、Flash CS、AutoCAD、Office等软件的安装与卸载，精通Windows Server、OSX、Unix、Lunix等操作系统的开关机，现求一份互联网科技公司端茶倒水的工作，不知您司能给到年薪888吗？
