### ISSUE TITLE
Apologize for some Chinese issues | 为一些中文 Issues 致歉

### ISSUE THREAD

**Issue by liangchenhe55** [chrislgarry/Apollo-11#476]
As you can see, there are some low quality chinese issues. As a chinese student I want to apologize first.

But please believe that uncivilized chinese people are only a few. There are many people in China who love technology and are willing to share it. We want to build an excellent community together.

Forgive me for poor english :(

---

正如你所见，Issues 有一些低质量的中文条目。作为一名中国学生我想先向各位道歉。

但是请相信，不文明的人只是少数。有许多的中国人民热爱技术、乐于分享。我们希望一切建立一个优秀的社区。

请原谅我英文不好 :(

**Comment by watershade** [comment]
Apologize too. I don't believe our people can be so follish and boorish to technology. Give my respect to this project.

**Comment by nyer** [comment]
别人干的事，他们自己道歉

**Comment by HandsomeKang** [comment]
I feel so sorry for our bad behavior.

**Comment by liangchenhe55** [comment]
> 别人干的事，他们自己道歉

话是没错。但是我们都是中国人，哪怕为了自己的未来也得帮忙一起维护中国人的形象。

---

That's right. Since we are all Chinese, just for our own future, we have to help maintain the image of the Chinese people together.

**Comment by qwas982** [comment]
为什么要道歉?莫名其妙.
你不会是山东大学(或与其有相似风气大学)教出来的崇洋媚外学生吧?
中文汉字汉语使你感到自卑吗?

**Comment by liangchenhe55** [comment]
> 为什么要道歉?莫名其妙.
> 你不会是山东大学(或与其有相似风气大学)教出来的崇洋媚外学生吧?
> 中文汉字汉语使你感到自卑吗?

可能我没说清楚，并不是因为中文而道歉，而是因为许多中文 issues 是低质量的，例如广告。我已经修改了原文以便更好地表述。

PS：英文是通用性最高的语言，在这样一个国际社区使用英文可以提高沟通效率。这与文化自信没有关系。当然，使用中文也不是不可以。再次强调，是为了内容而致歉。

**Comment by qwas982** [comment]
> > 为什么要道歉?莫名其妙.
> > 你不会是山东大学(或与其有相似风气大学)教出来的崇洋媚外学生吧?
> > 中文汉字汉语使你感到自卑吗?
> 
> 可能我没说清楚，并不是因为中文而道歉，而是因为许多中文 issues 是低质量的，例如广告。我已经修改了原文以便更好地表述。
> 
> PS：英文是通用性最高的语言，在这样一个国际社区使用英文可以提高沟通效率。这与文化自信没有关系。当然，使用中文也不是不可以。再次强调，是为了内容而致歉。

我算是明白为什么毛大爷要搞文 革格了,果然是酸腐文人,对外舔资本主义列强添得兴致高昂,对内在本国明搞暗搞资本主义,搞得社会底层生活艰难艰辛痛苦不堪,甚至拖累国家经济发展,果然是毒源!活该被批斗!毕竟这是因你们的本质而诞生的惩罚方式!中国很有必要再来一次文 
 革!你以为文 革是革谁?!  就是革你们这群反革命!
毛大爷那一代人费九牛二虎之力要推翻的东西,经过改开40年又出现在中华大地上,不可思议.

**Comment by linfili** [comment]
> > > 为什么要道歉?莫名其妙.
> > > 你不会是山东大学(或与其有相似风气大学)教出来的崇洋媚外学生吧?
> > > 中文汉字汉语使你感到自卑吗?
> > 
> > 
> > 可能我没说清楚，并不是因为中文而道歉，而是因为许多中文 issues 是低质量的，例如广告。我已经修改了原文以便更好地表述。
> > PS：英文是通用性最高的语言，在这样一个国际社区使用英文可以提高沟通效率。这与文化自信没有关系。当然，使用中文也不是不可以。再次强调，是为了内容而致歉。
> 
> 我算是明白为什么毛大爷要搞文 革格了,果然是酸腐文人,对外舔资本主义列强添得兴致高昂,对内在本国明搞暗搞资本主义,搞得社会底层生活艰难艰辛痛苦不堪,甚至拖累国家经济发展(经济泡沫,经济陷阱),果然是毒源!活该被批斗!毕竟这是因你们的本质而诞生的惩罚方式!中国很有必要再来一次文
> 革!你以为文 革是革谁?! 就是革你们这群反革命!
> 毛大爷那一代人费九牛二虎之力要推翻的东西,经过改开40年又出现在中华大地上,不可思议.

I feel shameful for you as a Chinese.
People like you are not qualified to be a DEVELOPER.
You pulled down the qualities of Chinese programmers in front of the world.
Shame on you!

**Comment by qwas982** [comment]
> > > > 为什么要道歉?莫名其妙.
> > > > 你不会是山东大学(或与其有相似风气大学)教出来的崇洋媚外学生吧?
> > > > 中文汉字汉语使你感到自卑吗?
> > > 
> > > 
> > > 可能我没说清楚，并不是因为中文而道歉，而是因为许多中文 issues 是低质量的，例如广告。我已经修改了原文以便更好地表述。
> > > PS：英文是通用性最高的语言，在这样一个国际社区使用英文可以提高沟通效率。这与文化自信没有关系。当然，使用中文也不是不可以。再次强调，是为了内容而致歉。
> > 
> > 
> > 我算是明白为什么毛大爷要搞文 革格了,果然是酸腐文人,对外舔资本主义列强添得兴致高昂,对内在本国明搞暗搞资本主义,搞得社会底层生活艰难艰辛痛苦不堪,甚至拖累国家经济发展(经济泡沫,经济陷阱),果然是毒源!活该被批斗!毕竟这是因你们的本质而诞生的惩罚方式!中国很有必要再来一次文
> > 革!你以为文 革是革谁?! 就是革你们这群反革命!
> > 毛大爷那一代人费九牛二虎之力要推翻的东西,经过改开40年又出现在中华大地上,不可思议.
> 
> I feel shameful for you as a Chinese.
> People like you are not qualified to be a DEVELOPER.
> You pulled down the qualities of Chinese programmers in front of the world.
> Shame on you!

你是丑垃圾,崇洋媚外,我呸,不知廉耻.

**Comment by cyp0633** [comment]
Some people are ruining the issue page and some of them are even ruining the apology?
That's such a pity.
另外，尊重别人的项目并不代表崇洋媚外。如果是中国人开的项目，某些人会再“啤酒饮料矿泉水”吗？
没素质咯，大家不要和他们闹。
真希望GitHub也有一个屏蔽功能。或者GFW应该精准墙一下~

**Comment by qwas982** [comment]
一堆舔洋大人舔出快感的沙雕,
尼玛你洋大人刚刚表达了对你们这群野狗的厌恶,https://www.oschina.net/news/108334/chinese-repos-are-ruining-the-github-trending-page
你又不厌其烦地去舔你洋大人拉出来的新鲜屎.
你也是够牛逼, 咋滴,你还不允许别人自由发言了? 这么想当美分,竟然不知道第一修正案说的是啥.当狗当得很失败呀.
