### ISSUE TITLE
Salute  to the GREAT FIRST STEP

### ISSUE THREAD

**Issue by lawrencewu** [chrislgarry/Apollo-11#479]
Salute  to the GREAT FIRST STEP

**Comment by drewster99** [comment]
I seriously wish I could get this thread to STOP emailing me.  I’ve muted the thread.  I’ve unsubscribed.  And I’m still getting dozens of emails a day.

**Comment by oldmud0** [comment]
@drewster99 If you unsubscribe, you only unsubscribe to one issue - you have to unwatch the repository as  well.
