### ISSUE TITLE
Issue tracker should be disabled

### ISSUE THREAD

**Issue by anderbubble** [chrislgarry/Apollo-11#48]
The issue tracker for this repository should be disabled.

https://www.reddit.com/r/programming/comments/4s37pk/the_code_that_took_america_to_the_moon_was_just/d56boyc

**Comment by Kangaroonicorn** [comment]
I agree. These issues are getting ridiculous. 
I say we launch the thing and just test it in production.

**Comment by chrislgarry** [comment]
Although I agree they are getting out of hand, it's not worth losing access to issue [#3](https://github.com/chrislgarry/Apollo-11/issues/3)

**Comment by Imagebard** [comment]
NO FUN ALLOWED

**Comment by whit537** [comment]
> Although I agree they are getting out of hand

@chrislgarry You can also [lock issues](https://github.com/blog/1847-locking-conversations) to dampen some of the noise once a joke has worn off. :)
