### ISSUE TITLE
代码我已经下载下来了，请问飞船我去哪领？

### ISSUE THREAD

**Issue by panfeng-Hn** [chrislgarry/Apollo-11#480]

**Comment by CheneyH** [comment]
我做个申请页面？

**Comment by hsun924** [comment]
http://www.cmse.gov.cn

**Comment by KennyWho** [comment]
去你妈逼里领。

**Comment by jvedi** [comment]
丢人丢到国际上来了，别人致敬技术和这个伟大的项目，而一些有害垃圾到这里秀下限。

**Comment by panfeng-Hn** [comment]
> 去你妈逼里领。

傻X

**Comment by huanglilei** [comment]
你妈死了 臭傻逼 恶心死了

**Comment by panfeng-Hn** [comment]
> 你妈死了 臭傻逼 恶心死了

就是要恶心死你这个杠精

**Comment by cannotbeblank** [comment]
你妈死了

**Comment by dcy0701** [comment]
你妈死了

**Comment by curse-zhina** [comment]
去你妈逼里领

**Comment by curse-zhina** [comment]
死妈杠精玩意儿,还说别人是杠精

**Comment by panfeng-Hn** [comment]
你们继续骂，我就当在看狗叫。请继续！！！

**Comment by JoelTsui** [comment]
应该把你加入到黑名单

**Comment by pihao** [comment]
![Snip20190720_2](https://user-images.githubusercontent.com/3308394/61575184-5c167680-aafb-11e9-9cc0-16b26be81951.png)
举报吧

**Comment by zhaoweijing2003** [comment]
素质素质!

**Comment by ddzy** [comment]
> 丢人丢到国际上来了，别人致敬技术和这个伟大的项目，而一些有害垃圾到这里秀下限。

那么请问圣母, 他的下限在哪里? 别人没有一句侮辱、贬低该`repo`的言语, 你的下限又在哪里?

**Comment by AnonymousIIIII** [comment]
？？
---原始邮件---
发件人:"三年级老猫"<notifications@github.com>
发送时间:2019年7月20日 星期六 下午8:16
收件人:"chrislgarry/Apollo-11"<Apollo-11@noreply.github.com>
抄送:"Subscribed"<subscribed@noreply.github.com>
主题:Re: [chrislgarry/Apollo-11] 代码我已经下载下来了，请问飞船我去哪领？ (#480)

丢人丢到国际上来了，别人致敬技术和这个伟大的项目，而一些有害垃圾到这里秀下限。

那么请问圣母, 他的下限在哪里? 别人没有一句侮辱、贬低该repo的言语, 你的下限又在哪里?

&mdash;

**Comment by AnonymousIIIII** [comment]
我没说过这样的话啊，我是一名高中学生，也很热爱代码，我没说过这些话啊，可以加微信私聊吗？交个朋友也好
---原始邮件---
发件人:"三年级老猫"<notifications@github.com>
发送时间:2019年7月20日 星期六 下午8:16
收件人:"chrislgarry/Apollo-11"<Apollo-11@noreply.github.com>
抄送:"Subscribed"<subscribed@noreply.github.com>
主题:Re: [chrislgarry/Apollo-11] 代码我已经下载下来了，请问飞船我去哪领？ (#480)

丢人丢到国际上来了，别人致敬技术和这个伟大的项目，而一些有害垃圾到这里秀下限。

那么请问圣母, 他的下限在哪里? 别人没有一句侮辱、贬低该repo的言语, 你的下限又在哪里?

&mdash;

**Comment by qwas982** [comment]
觉得丢人的那群人的心理究竟是怎样形成的,我很好奇.

**Comment by KennyWho** [comment]
github issue 不是让你玩梗 秀智商 玩幽默的地方，麻烦去微博 朋友圈发，一点问题没有。你这种傻逼行为，不配让我跟你好好说话，你有素质，我就有素质，你没素质，我没必要跟你讲，你听不懂，上面说圣母的弟弟，你妈是圣母吗，那我想kkp

**Comment by AnonymousIIIII** [comment]
嗯嗯
---原始邮件---
发件人:"leng gu du"<notifications@github.com>
发送时间:2019年7月20日 星期六 下午8:26
收件人:"chrislgarry/Apollo-11"<Apollo-11@noreply.github.com>
抄送:"INnoVation"<596033559@qq.com>;"Comment"<comment@noreply.github.com>
主题:Re: [chrislgarry/Apollo-11] 代码我已经下载下来了，请问飞船我去哪领？ (#480)

觉得丢人的那群人的心理究竟是怎样形成的,我很好奇.

&mdash;

**Comment by KennyWho** [comment]
智商是个好东西，你在你家卧室拉屎吗？还是你用嘴吃屎？issue 请问 你怎么理解？github是微博还是你朋友圈，自己丢人还他妈有理了？那你实名截图发公司群里，我看看公司人觉得你幽默还是你傻逼。

**Comment by qwas982** [comment]
病癫邪鬼,红门恐丑,太多,太多,来势凶残,楼主小心.

**Comment by fuchangle** [comment]
SB，你觉得你很幽默吗？在这儿丢人
