### ISSUE TITLE
都是汇编，看不懂啊

### ISSUE THREAD

**Issue by kakaxi-lin** [chrislgarry/Apollo-11#481]

**Comment by yoyo837** [comment]
看不懂的项目你是不是都要开个issue？别搞得自己像苍蝇一样好不好, 其他国人在这里受偏见的时候不见你发言...

**Comment by WeilunFong** [comment]
I hate such stupid person, even if I'm Chinese, too. | 同為中國人，為你這樣隨意發佈issue的行為感到丟臉。

**Comment by 4thirteen2one** [comment]
不懂就学去啊......人家开源出来给你看就好不过了，你还指望让人家包教包会一条龙服务？伸手党当习惯了吗发这种毫无意义的issue......而且用的还是卡卡西的头像...... Shame on you.

**Comment by AshLeung** [comment]
兄dei你火了呀。

**Comment by yoyo837** [comment]
Ask the owner to close the issue and lock it, Please...

**Comment by ysy950803** [comment]
哥们不能哗众取宠哦！

**Comment by cerebrowang** [comment]
看不懂回去学，看懂了再来

**Comment by tlztanluhe** [comment]
哪来的丢人的贱货

**Comment by yt-theme** [comment]
因为你一个issues中国开发者会被蔑视

**Comment by thinkinweb** [comment]
99元汇编包教包会，不会退款。

**Comment by shaoduo123** [comment]
为什么这条中文issue没被closed ，大家自己都想想吧。这是一种歧视？

**Comment by yoyo837** [comment]
@shaoduo123 搜索全文就你在提‘歧视’二字。。。没有被关闭可能是时差，可能是无视，可能是任何其他原因，但都不是随意开issue的理由，任何项目都不喜欢随意开issue的人...

**Comment by aqutor** [comment]
Instead of learning, you choose to open a new issue. I don't know if this the way you learn. I assume you will never learn.

**Comment by logic-wei** [comment]
Please say something meaningful.I hope GitHub could be a serious platform rather than "GayHub" like what we have joked.

**Comment by oldmud0** [comment]
Can't believe the number of downvotes these posts receive within two hours.
