### ISSUE TITLE
据说某国特工九死一生拿到了NASA太空火箭发射程序源代码的最后几页

### ISSUE THREAD

**Issue by Sigmn** [chrislgarry/Apollo-11#482]
据说某国特工九死一生偷到了NASA太空火箭发射程序源代码的最后几页，代码是：}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}

**Comment by hooverwang** [comment]
hahahaha

**Comment by KennyWho** [comment]
我想给你妈烧个香

**Comment by xiaohuilam** [comment]
别出来丢人现眼了， 小鳖三。滚出 Github。
Get back and fuck you ass, xb3. Leave the plannet earth alone.

**Comment by yoyo837** [comment]
不要在这里发些技术无关的，有其他兴趣的应该去twitter发言...

**Comment by watershade** [comment]
Close it as soon as possible

**Comment by dcy0701** [comment]
特工把你妈干死了

**Comment by hollykunge** [comment]
唯一一个可以接触外接的网站 中国人怎么就不能在这发泄一下了？

**Comment by JoelTsui** [comment]
丢人的傻逼玩意

**Comment by qwas982** [comment]
> 丢人的傻逼玩意

为什么丢人?莫名其妙.
你不会是山东大学(或与其有相似风气大学)教出来的崇洋媚外学生吧?
中文汉字汉语使你感到自卑吗?

**Comment by JoelTsui** [comment]
在这种地方灌水不丢人是吧。垃圾。你觉得很自豪，可以，叫什么名字，哪个大学的？在哪儿上班呢？说出来让大家敬佩敬佩你。啥水平拿出来看看有没有资格说别人崇洋媚外

**Comment by pihao** [comment]
![Snip20190720_2](https://user-images.githubusercontent.com/3308394/61575198-87996100-aafb-11e9-8f31-8d6830fb1ddd.png)

**Comment by qwas982** [comment]
> 在这种地方灌水不丢人是吧。垃圾。你觉得很自豪，可以，叫什么名字，哪个大学的？在哪儿上班呢？说出来让大家敬佩敬佩你。啥水平拿出来看看有没有资格说别人崇洋媚外

我算是明白为什么毛大爷要搞文 革格了,果然是酸腐文人,对外舔资本主义列强添得兴致高昂,对内在本国明搞暗搞资本主义,搞得社会底层生活艰难艰辛痛苦不堪,甚至拖累国家经济发展(经济泡沫,经济陷阱),果然是毒源!活该被批斗!毕竟这是因你们的本质而诞生的惩罚方式!中国很有必要再来一次文 革!你以为文 革是革谁?! 就是革你们这群反革命!
毛大爷那一代人费九牛二虎之力要推翻的东西,经过改开40年又重新出现在中华大地上,不可思议.

**Comment by JoelTsui** [comment]
@qwas982 哈哈哈哈哈哈，真的是笑死我了，没想到你这种余孽还有，看了你的github，还顺便搜了一下知乎上的你，真的是要笑死我。我真的没想到，这个世界上还有你这种人存在。

**Comment by qwas982** [comment]
@JoelTsui  
毕竟你是沙雕瘾癌毒邪病癫娼呀, 
我也没想到,本国推翻三座大山已经过去半个多世纪后,这个世界上也还有你们这群抱着三座大山不放的腐臭人存在。地富反坏右们,等着被清算吧!

**Comment by vince7839** [comment]
你觉得很搞笑？真尼玛丢净cn开发者的脸 你知不知道这项目issure页面的这种中文水帖在各论坛都被骂了个遍？

**Comment by JoelTsui** [comment]
> 你觉得很搞笑？真尼玛丢净cn开发者的脸 你知不知道这项目issure页面的这种中文水帖在各论坛都被骂了个遍？

大哥，看清楚啊，友军

**Comment by o-u-p** [comment]
> 唯一一个可以接触外接的网站 中国人怎么就不能在这发泄一下了？
限制的是你这种技术不行的人， 我任何外网都能上

**Comment by Jhonsem** [comment]
嘴巴嘟嘟 嘟嘟嘟

**Comment by Rinacm** [comment]
> @JoelTsui
> 毕竟你是沙雕瘾癌毒邪病癫娼呀,
> 我也没想到,本国推翻三座大山已经过去半个多世纪后,这个世界上也还有你们这群抱着三座大山不放的腐臭人存在。地富反坏右们,等着被清算吧!

哈哈，想不到github上也有五毛

**Comment by Rinacm** [comment]
> > 在这种地方灌水不丢人是吧。垃圾。你觉得很自豪，可以，叫什么名字，哪个大学的？在哪儿上班呢？说出来让大家敬佩敬佩你。啥水平拿出来看看有没有资格说别人崇洋媚外
> 
> 我算是明白为什么毛大爷要搞文 革格了,果然是酸腐文人,对外舔资本主义列强添得兴致高昂,对内在本国明搞暗搞资本主义,搞得社会底层生活艰难艰辛痛苦不堪,甚至拖累国家经济发展(经济泡沫,经济陷阱),果然是毒源!活该被批斗!毕竟这是因你们的本质而诞生的惩罚方式!中国很有必要再来一次文 革!你以为文 革是革谁?! 就是革你们这群反革命!
> 毛大爷那一代人费九牛二虎之力要推翻的东西,经过改开40年又重新出现在中华大地上,不可思议.

把"毛爷爷废了九牛二虎之力推翻的东西"给复辟了的不是敬爱的"邓爷爷"吗？你在这里不可思议什么呢？

**Comment by Rinacm** [comment]
@qwas982 stop sending emoji and answer my question plz

**Comment by qwas982** [comment]
@Rinacm  
你是美分,崇洋媚外,我呸,不知廉耻.
你想用你精西,和你洋大人的价值观来要求我吗?
你想把你当狗当出的快感自己觉得舒服所以就要强加给我吗?
烂人,恶臭!

**Comment by Rinacm** [comment]
> @Rinacm
> 你是美分,崇洋媚外,我呸,不知廉耻.
> 你想用你精西,和你洋大人的价值观来要求我吗?
> 你想把你当狗当出的快感自己觉得舒服所以就要强加给我吗?
> 烂人,恶臭!

算了算了你这么可爱真的不想骂你了，但是你真的是把我整笑了

**Comment by qwas982** [comment]
> > @Rinacm
> > 你是美分,崇洋媚外,我呸,不知廉耻.
> > 你想用你精西,和你洋大人的价值观来要求我吗?
> > 你想把你当狗当出的快感自己觉得舒服所以就要强加给我吗?
> > 烂人,恶臭!
> 
> 算了算了你这么可爱真的不想骂你了，但是你真的是把我整笑了

一堆舔洋大人舔出快感的沙雕,
尼玛你洋大人刚刚表达了对你们这群野狗的厌恶,https://www.oschina.net/news/108334/chinese-repos-are-ruining-the-github-trending-page
 ,你又不厌其烦地去舔你洋大人拉出来的新鲜屎.
你也是够牛逼, 咋滴,你还不允许别人自由发言了? 这么想当美分,竟然不知道第一修正案说的是啥.当狗当得很失败呀..

**Comment by NanamiArihara** [comment]
> > > @Rinacm
> > > 你是美分,崇洋媚外,我呸,不知廉耻.
> > > 你想用你精西,和你洋大人的价值观来要求我吗?
> > > 你想把你当狗当出的快感自己觉得舒服所以就要强加给我吗?
> > > 烂人,恶臭!
> > 
> > 
> > 算了算了你这么可爱真的不想骂你了，但是你真的是把我整笑了
> 
> 一堆舔洋大人舔出快感的沙雕,
> 尼玛你洋大人刚刚表达了对你们这群野狗的厌恶,https://www.oschina.net/news/108334/chinese-repos-are-ruining-the-github-trending-page
> ,你又不厌其烦地去舔你洋大人拉出来的新鲜屎.
> 你也是够牛逼, 咋滴,你还不允许别人自由发言了? 这么想当美分,竟然不知道第一修正案说的是啥.当狗当得很失败呀..

你说别人恶臭，他是中国人，你就是说中国人恶臭。既然中国人恶臭，你是中国人，你恶臭。你也恶臭，你就和他一样，说的都是屁话，如果你说你不恶臭，是放屁。卖国贼是句句屁话的，所以你是卖国贼。因为我骂你，所以我爱国，爱国的人说的话最有价值，所以我骂你很对，你就是恶臭的卖国贼

**Comment by qwas982** [comment]
> > > > @Rinacm
> > > > 你是美分,崇洋媚外,我呸,不知廉耻.
> > > > 你想用你精西,和你洋大人的价值观来要求我吗?
> > > > 你想把你当狗当出的快感自己觉得舒服所以就要强加给我吗?
> > > > 烂人,恶臭!
> > > 
> > > 
> > > 算了算了你这么可爱真的不想骂你了，但是你真的是把我整笑了
> > 
> > 
> > 一堆舔洋大人舔出快感的沙雕,
> > 尼玛你洋大人刚刚表达了对你们这群野狗的厌恶,https://www.oschina.net/news/108334/chinese-repos-are-ruining-the-github-trending-page
> > ,你又不厌其烦地去舔你洋大人拉出来的新鲜屎.
> > 你也是够牛逼, 咋滴,你还不允许别人自由发言了? 这么想当美分,竟然不知道第一修正案说的是啥.当狗当得很失败呀..
> 
> 你说别人恶臭，他是中国人，你就是说中国人恶臭。既然中国人恶臭，你是中国人，你恶臭。你也恶臭，你就和他一样，说的都是屁话，如果你说你不恶臭，是放屁。卖国贼是句句屁话的，所以你是卖国贼。因为我骂你，所以我爱国，爱国的人说的话最有价值，所以我骂你很对，你就是恶臭的卖国贼
> 
> 你说我恶臭，我是中国人，你就是说中国人恶臭，就是在骂中国不好，你是外国人么？为什么不到外国去？可惜外国人看你不起……

你这种恶臭癫7吐出的狺狺狂吠,一句话就能回答了,
因为你是**爱国贼**啊.

**Comment by yoyo837** [comment]
@qwas982 你在这里带节奏，还发表政治言论。先不说这是国际社区应该尽量使用国际语言，而是这个issue的内容毫无异议存粹是灌水，换成其他语言的发出来也是一样讨厌，只是因为很多人看不懂才没参与进来，根本就没人在提说汉字自己觉得丢人的事。 

**重点是无意义的灌水issue**，repo浏览者就必须被迫接受看到，和中文不中文无关，大多数情况都是国人在干这种事，比如上次Node.js之父的新项目就是这样。就好比总接到骚扰电话一样。再说回语言，至于为什么国际语言不是中文，你应该去问殖民者。

总之@qwas982 你的言论根本让人觉得就莫名其妙。

**Comment by qwas982** [comment]
> @qwas982 你在这里带节奏，还发表政治言论。先不说这是国际社区应该尽量使用国际语言，而是这个issue的内容毫无意义存粹是灌水，换成其他语言的发出来也是一样讨厌，只是因为很多人看不懂才没参与进来，根本就没人在提说汉字自己觉得丢人的事。
> 
> **重点是无意义的灌水issue**，repo浏览者就必须被迫接受看到，和中文不中文无关，大多数情况都是国人在干这种事，比如上次Node.js之父的新项目就是这样。就好比总接到骚扰电话一样。再说回语言，至于为什么国际语言不是中文，你应该去问殖民者。
> 
> 总之@qwas982 你的言论根本让人觉得就莫名其妙。

不好意思哈,我就看不惯贬低我中华文明的存在,甭管你是外国鬼佬还是跪舔洋人的舔狗.

**Comment by Rinacm** [comment]
> @Rinacm
> 你是美分,崇洋媚外,我呸,不知廉耻.
> 你想用你精西,和你洋大人的价值观来要求我吗?
> 你想把你当狗当出的快感自己觉得舒服所以就要强加给我吗?
> 烂人,恶臭!


> > @qwas982 你在这里带节奏，还发表政治言论。先不说这是国际社区应该尽量使用国际语言，而是这个issue的内容毫无意义存粹是灌水，换成其他语言的发出来也是一样讨厌，只是因为很多人看不懂才没参与进来，根本就没人在提说汉字自己觉得丢人的事。
> > **重点是无意义的灌水issue**，repo浏览者就必须被迫接受看到，和中文不中文无关，大多数情况都是国人在干这种事，比如上次Node.js之父的新项目就是这样。就好比总接到骚扰电话一样。再说回语言，至于为什么国际语言不是中文，你应该去问殖民者。
> > 总之@qwas982 你的言论根本让人觉得就莫名其妙。
> 
> 不好意思哈,我就看不惯贬低和嘲讽我中华文明的存在,甭管你是外国鬼佬还是跪舔洋人的舔狗.
> 我当然知道世界各族各国家都是有好人恶人之别的.你看好,我可没以偏概全地说所有人哈.

恐怕你这秀智商的言论已经不仅仅是以偏概全的的问题了，建议去精神病院看一看，免得日后做出类似京都动画纵火犯之类的事情

**Comment by qwas982** [comment]
> > @Rinacm
> > 你是美分,崇洋媚外,我呸,不知廉耻.
> > 你想用你精西,和你洋大人的价值观来要求我吗?
> > 你想把你当狗当出的快感自己觉得舒服所以就要强加给我吗?
> > 烂人,恶臭!
> 
> > > @qwas982 你在这里带节奏，还发表政治言论。先不说这是国际社区应该尽量使用国际语言，而是这个issue的内容毫无意义存粹是灌水，换成其他语言的发出来也是一样讨厌，只是因为很多人看不懂才没参与进来，根本就没人在提说汉字自己觉得丢人的事。
> > > **重点是无意义的灌水issue**，repo浏览者就必须被迫接受看到，和中文不中文无关，大多数情况都是国人在干这种事，比如上次Node.js之父的新项目就是这样。就好比总接到骚扰电话一样。再说回语言，至于为什么国际语言不是中文，你应该去问殖民者。
> > > 总之@qwas982 你的言论根本让人觉得就莫名其妙。
> > 
> > 
> > 不好意思哈,我就看不惯贬低和嘲讽我中华文明的存在,甭管你是外国鬼佬还是跪舔洋人的舔狗.
> > 我当然知道世界各族各国家都是有好人恶人之别的.你看好,我可没以偏概全地说所有人哈.
> 
> 恐怕你这秀智商的言论已经不仅仅是以偏概全的的问题了，建议去精神病院看一看，免得日后做出类似京都动画纵火犯之类的事情

哎呀,你已经表达过你欲当跪舔狗的愿望了呀,我已经知道了,无需重复.
小心你狗主子要索你的狗命哟.哈哈哈哈哈.
索你狗命时,记得看清楚是谁索的,肆意嫁祸他人那你就不是是否有精神病的问题那么简单了.
