### ISSUE TITLE
Front-end interview 3+1 per day

### ISSUE THREAD

**Issue by haizhilin2013** [chrislgarry/Apollo-11#484]
> The world's most comprehensive front-end interview questions!

* [Vue 248 questions](https://github.com/haizlin/fe-interview/blob/master/lib/Vue.md)
* [React 328 questions](https://github.com/haizlin/fe-interview/blob/master/lib/React.md)

[Look at it](https://github.com/haizlin/fe-interview)

**Comment by yxkhaha** [comment]
nb

**Comment by MorningJack** [comment]
cool

**Comment by dcy0701** [comment]
你妈死了 别在这恶心人

**Comment by 402392291** [comment]
不错不错

**Comment by nyer** [comment]
this issue is not relevant with this project, please close it.  by the way ,  it is impolite to advertise here

**Comment by KennyWho** [comment]
`I love my family very much, cherish the ownership, health is blessing`

你是不是孤儿啊，你还有🏠吗？
