### ISSUE TITLE
Handling Issues

### ISSUE THREAD

**Issue by chrislgarry** [chrislgarry/Apollo-11#485]
Im currently working on the best way to deal with recent influx of issues. It seems there arent any features for dealing with this problem in bulk, so I submitted a feature request to bulk flag/delete in the UI (pretty sure it can be done using the API via a simple python script) and to limit issue creation etc. to accounts older than age X. Ill close this once we have a long-term solution. Unfortunately, those who want to watch our repository are being bombarded with nonsense notifications, so this is important. Its important to note that most of these issues are jokes which are ok, but this could become problematic if it gets out of hand.

**Comment by dwiyatci** [comment]
I can understand and relate though 😅 🚀 

![D_rv8nAW4AE6lrW](https://user-images.githubusercontent.com/4405796/61575428-e515b980-aacb-11e9-8aae-cb6276a79a23.jpg)

**Comment by medusar** [comment]
@dwiyatci I just wonder from where did you get these results ?

**Comment by oldmud0** [comment]
I'd like to publicize the analytics for this repo:
![GitHub analytics](https://user-images.githubusercontent.com/5247009/61581379-367d7300-aae3-11e9-8172-32e19f288bed.png)
Last time the repo flared up like this was about 2 years ago. I don't remember at what number it peaked at, but this is a magnitude larger than the traffic we received at that time. GitHub is pretty good on spam, but "user-generated noise" can accumulate fairly quickly with tends of thousands of visitors.

**Comment by suhanyujie** [comment]
Hi, I'm Chinese, and I feeling shame for those bad issues. But those people aren't standing all of us, I believe most of Chinese are friendly, for GitHub, for "Apollo-11"  ^ ^

**Comment by chrislgarry** [comment]
@suhanyujie dont worry, joking is ok! We get a lot of joke issues from English speakers as well. But if the issues are violence, hate speech, etc, towards others, then we have to try to keep it peaceful.

**Comment by chrislgarry** [comment]
@oldmud0 that's some insightful data. Perhaps we prepare before the anniversary each year. Scripts for bulk deletion via the REST API, etc.

**Comment by caridle** [comment]
> Hi, I'm Chinese, and I feeling shame for those bad issues. But those people aren't standing all of us, I believe most of Chinese are friendly, for GitHub, for "Apollo-11" ^ ^

你是中国人的悲剧，跪久了。社区言论谁都可以灌水，这是约定俗成的规矩。

**Comment by liyujiang-gzu** [comment]
向伟大的作者致敬，我想这几天那么多中国朋友滥用issue凑热闹并无恶意，纯粹是增加参与感，毕竟阿波罗11号这么伟大的工程从小中国教科书里就说了，做梦也想不到我们有朝一日还能看到它的源码。

**Comment by qq1037861239** [comment]
just as you know, the issues wrote by Chinese is good well joking, that is a lively way for us to cheering for it. It's a global site contains the multicultural, and I think now this project is not a technical problem any more, so, I don't think that's inappropriate. Unless you think these people are not earthlings. some people think they are gentlemen, despising this kind of celebrating, how does that differentiate from American style hypocrisy? they are all Trumps!!!!!

**Comment by wangyongquan666** [comment]
so, what happen?

**Comment by oldmud0** [comment]
@wopian Let's stop categorically locking Chinese-only issues as spam - if they don't seem relevant, just close them, but locking as spam is becoming excessive.

@qq1037861239 I apologize for the locking. I cannot pretend to know Chinese to determine if it is really spam or not.

**Comment by jhoneybee** [comment]
@oldmud0  Although GitHub is a diversified community, I think we should use English to communicate. This should be actively recommended. I don't think we should apologize for the lock-in of Chinese. (PS: I come to China)

> I'm Chinese , I'm really sorry

**Comment by qq1037861239** [comment]
> @wopian Let's stop categorically locking Chinese-only issues as spam - if they don't seem relevant, just close them, but locking as spam is becoming excessive.
> 
> @qq1037861239 I apologize for the locking. I cannot pretend to know Chinese to determine if it is really spam or not, and the downvotes are becoming a little misleading.

no, don's need apologize, that nothing. It is interesting that most of those people against Chinese joking is Chinese, they someone attacked me on my project page issues.
they say the issues have to be serious and technical, how? Real funny, just like someone told me I don't know how to play github.

**Comment by jhoneybee** [comment]
@qq1037861239  

https://github.com/seajs/seajs/issues/545 , We should respect the open source community and maintain it. We should not abuse it.

**Comment by jhoneybee** [comment]
> > @wopian Let's stop categorically locking Chinese-only issues as spam - if they don't seem relevant, just close them, but locking as spam is becoming excessive.
> > @qq1037861239 I apologize for the locking. I cannot pretend to know Chinese to determine if it is really spam or not, and the downvotes are becoming a little misleading.
> 
> no, don't need apologize, that's nothing. It is interesting that most of those people against Chinese joking is Chinese, they someone attacked me on my project page issues.
> they say the issues have to be serious and technical, how? Real funny, just like someone told me I don't know how to play github.

https://github.com/seajs/seajs/issues/545 , We should respect the open source community and maintain it. We should not abuse it.

**Comment by qq1037861239** [comment]
> > > @wopian Let's stop categorically locking Chinese-only issues as spam - if they don't seem relevant, just close them, but locking as spam is becoming excessive.
> > > @qq1037861239 I apologize for the locking. I cannot pretend to know Chinese to determine if it is really spam or not, and the downvotes are becoming a little misleading.
> > 
> > 
> > no, don't need apologize, that's nothing. It is interesting that most of those people against Chinese joking is Chinese, they someone attacked me on my project page issues.
> > they say the issues have to be serious and technical, how? Real funny, just like someone told me I don't know how to play github.
> 
> [seajs/seajs#545](https://github.com/seajs/seajs/issues/545) , We should respect the open source community and maintain it. We should not abuse it.

yes, you are right, but I think some harmless banter is not damage here. just like we also get joking in english here.

**Comment by jhoneybee** [comment]
> just as you know, the issues wrote by Chinese is good well joking, that is a lively way for us to cheering for it. github is a global site contains the multicultural, and I think now this project is not a technical problem any more, so, I don't think that's inappropriate. Unless you think these people are not earthlings. some people think they are gentlemen, despising this kind of celebrating, how does that differentiate from American style hypocrisy? they are all Trumps!!!!!

I hope you can take a good look at the code of conduct. It's a very good community and you don't want to destroy it (PS: Don't make life attacks).  

+ https://www.contributor-covenant.org/version/1/4/code-of-conduct.md

**Comment by jhoneybee** [comment]
> > > > @wopian Let's stop categorically locking Chinese-only issues as spam - if they don't seem relevant, just close them, but locking as spam is becoming excessive.
> > > > @qq1037861239 I apologize for the locking. I cannot pretend to know Chinese to determine if it is really spam or not, and the downvotes are becoming a little misleading.
> > > 
> > > 
> > > no, don't need apologize, that's nothing. It is interesting that most of those people against Chinese joking is Chinese, they someone attacked me on my project page issues.
> > > they say the issues have to be serious and technical, how? Real funny, just like someone told me I don't know how to play github.
> > 
> > 
> > [seajs/seajs#545](https://github.com/seajs/seajs/issues/545) , We should respect the open source community and maintain it. We should not abuse it.
> 
> yes, you are right, but I think some harmless banter is not damage here. just like we also get joking in english here.

If everyone talks about irrelevant topics, the real problems will be covered. This behavior is not advocated.

**Comment by qq1037861239** [comment]
> > just as you know, the issues wrote by Chinese is good well joking, that is a lively way for us to cheering for it. github is a global site contains the multicultural, and I think now this project is not a technical problem any more, so, I don't think that's inappropriate. Unless you think these people are not earthlings. some people think they are gentlemen, despising this kind of celebrating, how does that differentiate from American style hypocrisy? they are all Trumps!!!!!
> 
> I hope you can take a good look at the code of conduct. It's a very good community and you don't want to destroy it (PS: Don't make life attacks).
> 
> * https://www.contributor-covenant.org/version/1/4/code-of-conduct.md

yeah, I won't do that(attacked somebody), of course I respect it cause it's a great thing that human did. And I will listen to you who gives an opinion

**Comment by HaiyangDING** [comment]
We use issues as an effective way to communicate what needs to be done or what needs to be discussed. It is as simple as that. Being a Chinese you should be well aware that those issues in Chinese are not helping in any sense. If you want to celebrate, COOL, just go and find somewhere else, or create your own git project/repo on celebrating this, no problem.

**Comment by jiduofengyufan** [comment]
So we need to be calm, because we must understand clearly that most Chinese people always keep something only for a short while, and I believe that those useless Chinese issues will not be in flood in the near future.

**Comment by qq1037861239** [comment]
> We use issues as an effective way to communicate what needs to be done or what needs to be discussed. It is as simple as that. Being a Chinese you should be well aware that those issues in Chinese are not helping in any sense. If you want to celebrate, COOL, just go and find somewhere else, or create your own git project/repo on celebrating this, no problem.

I wonder if the author is in charge or you are

**Comment by HaiyangDING** [comment]
> > We use issues as an effective way to communicate what needs to be done or what needs to be discussed. It is as simple as that. Being a Chinese you should be well aware that those issues in Chinese are not helping in any sense. If you want to celebrate, COOL, just go and find somewhere else, or create your own git project/repo on celebrating this, no problem.
> 
> I wonder if the author is in charge or you are

It is very clear I am not in charge, but it is not relevant. It is all about trying to maintain a good atmosphere for efficient communicate, which is key to cooperate and innovation. Chinese or not, as long as you are a so-you-called earthling, and you are keen to help collaboration other than ruining it, you should follow the community code. 

I am out of the discussion, and if you feel like winning, feel free to celebrate. However, do you really believe your statements had ever earned any respect for us Chinese engineers?

**Comment by oldmud0** [comment]
@wopian I really, really think locking everything is causing more harm than good right now.

**Comment by liyujiang-gzu** [comment]
讨论真激烈啊！兄弟们建议用英语交流？抱歉，我用英文写不出来，只能借助翻译工具。
我认为github就是个全球化的多语言社区，凭啥就得必须用英语才能交流？老外不懂汉语，难道连翻译工具也不会用吗？
♥♥♥
What a heated discussion! Brothers suggest communicating in English? Sorry, I can't write in English. I can only use translation tools.
I think github is a global multilingual community. Why do we have to communicate in English? Foreigners don't know Chinese, can't they even use translation tools?

**Comment by V-GreenTea** [comment]
都是中国人，用中文能死？

**Comment by V-GreenTea** [comment]
都是中国人，用中文能死？

**Comment by qq1037861239** [comment]
> 都是中国人，用中文能死？
@V-GreenTea 这儿有无数的贵宾犬，他们看到汉字就恶心犯晕，那还能怎样

**Comment by caridle** [comment]
> 都是中国人，用中文能死？

对呀，坚决使用中文，让中文走向全世界，希望 cell、nature 和 science 全部使用中文或者中国人至少要使用中文文章，包括很多的 SCI、EI 论文。我们程序猿首先走在前列，使用中文说明开源程序。

**Comment by qq1037861239** [comment]
@HaiyangDING I just can't understand that why don't you pull requests if you think about anything in this project? why? why you think stubbornly there should be no anything like joking or Chinese? 
We are all individuals, no one stop you getting respect from the damn friendly upscale community!
Or maybe you should send an email to github telling them what a issue space should be.

**Comment by qq1037861239** [comment]
@HaiyangDING Let's stop talking about how to pull a issue. I am not stupid and I know clearly what thing are correct or not. I don't need anyone else to teach me how to use github.

**Comment by jiduofengyufan** [comment]
We can't deny that it is a diversified world, and we can't deny that github is the world's largest open source community that attracts developers around the world. However, what we hope is to communicate more effectively and quickly here.Like a friend of mine in Sichuan who spoke to me in pure Sichuan dialect, I couldn't understand him at all. I hope he can speak to me in Mandarin as much as possible.

**Comment by lilydjwg** [comment]
I have skimmed some Chinese issues, and...I ended up blocking almost all authors of them because they are impolite or meaningless. Sigh...btw, the only person I've blocked as spam previously is likely Chinese too.

@caridle in order to promote Chinese to the world, the first thing to not do is use dirty words to spam, creating an impression that Chinese are dirty. (I don't like nor use my local dialect because of the very same reason.)

(Chinese translation for last paragraph) @caridle 为了向全世界推广中文，第一件需要停止做的事情是使用脏话来制造 spam，给外人造成中文脏乱的印象。（我不喜欢也不用我的当地方言就是因为这个原因。）

**Comment by liyishuai** [comment]
1. As the [GitHub Community Guidelines](//help.github.com/en/articles/github-community-guidelines#building-a-strong-community) suggests, spamming repositories is by no means recommended:
    > People use GitHub to get work done and to be more productive. Off topic comments are a distraction (sometimes welcome, but usually not) from getting work done and being productive. Staying on topic helps produce positive and productive discussions.
2. GitHub is an inclusive community. Everyone has the right to use their favorite language, as long as they're contributive. Not all are experts in English. Even if someone can read English, they might not be confident in writing. We can encourage them to write clearly in their language, and find some enthusiastic collaborator to translate. That shouldn't be hard for popular languages like Chinese.
3. 面子是别人给的，脸是自己丢的。讨人嫌的不是语言，而是话语。代码库不是灌水的地方，请远离低级趣味。

**Comment by jhoneybee** [comment]
> @HaiyangDING Let's stop talking about how to pull a issue. I am not stupid and I know clearly what things are correct or not. I don't need anyone else to teach me how to use github.

You know exactly how to use github, but why don't you follow the community guidelines of github?

**Comment by yujiangshui** [comment]
Maybe GitHub can learn from StackOverflow, give every account a reputation score (based on the registered time, pull requests, contribution, and other people's report). And the repo admin can set the criteria (like reputation more than 15) to contribute or submit an issue to this project?

**Comment by qq1037861239** [comment]
> > @HaiyangDING Let's stop talking about how to pull a issue. I am not stupid and I know clearly what things are correct or not. I don't need anyone else to teach me how to use github.
> 
> You know exactly how to use github, but why don't you follow the community guidelines of github?
@jhoneybee 
Yes, usually we talk about technical questions when sub an issue. most of these issues in joking do not contain any attacked words or hate speech, some unfriendly will be closed. 


> @suhanyujie dont worry, joking is ok! We get a lot of joke issues from English speakers as well. But if the issues contain violence, hate speech, etc, towards others, then we have to try to keep it peaceful. Although it is hard for us to know which issues in Chinese are jokes and which are hateful speech, because we dont speak Chinese.

**Comment by oldmud0** [comment]
I don't understand what is being debated here. If there is something to be discussed, please keep it from being inflammatory; ad hominem is not tolerated. As for joke and off-topic issues, they will continue to be closed regardless of the language spoken. They are hidden away with all the other closed issues.

**Comment by qq1037861239** [comment]
def main():
    bye()
    quit()

if __name__ == '__main__':
    main()

**Comment by loopq** [comment]
because English is the most extensive language......

**Comment by V-GreenTea** [comment]
> 
> 
> because English is the most extensive language......

慕洋犬666。

**Comment by qwas982** [comment]
如果阅者访客看不惯-贬低和嘲讽和歧视我华夏文明与中文汉字汉语的那些慕洋犬们-的话,
请大声和踊跃地用中文汉字汉语发表自己的看法.
我观察到一个现象,为何在众多国际会议上,代表他那一国发言的人都是用他本国的语言?
经过搜索我找到的答案是;那是爱他的国和他的民族的表现,

**Comment by jhoneybee** [comment]
> 如果阅者访客看不惯-贬低和嘲讽和歧视我华夏文明与中文汉字汉语的那些慕洋犬们-的话,
> 请大声和踊跃地用中文汉字汉语发表自己的看法.
> 我观察到一个现象,为何在众多国际会议上,代表他那一国发言的人都是用他本国的语言?
> 经过搜索我找到的答案是;那是爱他的国和他的民族与文化的表现,并且,与会者是尊重这种行为的.
> 
> If the readers are not accustomed to - derogatory and ridiculous and discriminating against those HuaXia civilizations and Chinese symbol_Mandarin_Chinese character - the 慕mu洋yang犬quan们men -
> Please express your opinion in Chinese symbol_Mandarin_Chinese character in a loud and eager manner.
> I have observed a phenomenon. Why do people who speak on his behalf speak in his own language at many international conferences?
> After searching, I found the answer; that is the expression of the country that loves him and his nation and culture, and the participants respect this behavior.


Github is an academic community. The default language of communication is English. If you don't like English, you can go to CSDN or Zhihu . 

> Please upgrade GFW

**Comment by user-Mrh** [comment]
> 
> 
> > 如果阅者访客看不惯-贬低和嘲讽和歧视我华夏文明与中文汉字汉语的那些慕洋犬们-的话,
> > 请大声和踊跃地用中文汉字汉语发表自己的看法.
> > 我观察到一个现象,为何在众多国际会议上,代表他那一国发言的人都是用他本国的语言?
> > 经过搜索我找到的答案是;那是爱他的国和他的民族与文化的表现,并且,与会者是尊重这种行为的.
> > If the readers are not accustomed to - derogatory and ridiculous and discriminating against those HuaXia civilizations and Chinese symbol_Mandarin_Chinese character - the 慕mu洋yang犬quan们men -
> > Please express your opinion in Chinese symbol_Mandarin_Chinese character in a loud and eager manner.
> > I have observed a phenomenon. Why do people who speak on his behalf speak in his own language at many international conferences?
> > After searching, I found the answer; that is the expression of the country that loves him and his nation and culture, and the participants respect this behavior.
> 
> Github is an academic community. The default language of communication is English. If you don't like English, you can go to CSDN or Zhihu .
> 
> >为什么有些人总是看不惯自己的同胞使用自己母语来进行问题的讨论，我们承认有一些人在社区里发布垃圾言论但是只有中国会产生混蛋么？
我们抵触的只是以诋毁祖国文化来获取畸形的优越感的人。
你是个Easyboy？请收起你对着太平洋的屁股。
Why do some people always hate their compatriots using their own language to discuss problems? We admit that some people post rubbish in the community but only China produces assholes?
We are only against those who vilify the culture of their motherland in order to gain a distorted sense of superiority.

**Comment by jhoneybee** [comment]
> > > 如果阅者访客看不惯-贬低和嘲讽和歧视我华夏文明与中文汉字汉语的那些慕洋犬们-的话,
> > > 请大声和踊跃地用中文汉字汉语发表自己的看法.
> > > 我观察到一个现象,为何在众多国际会议上,代表他那一国发言的人都是用他本国的语言?
> > > 经过搜索我找到的答案是;那是爱他的国和他的民族与文化的表现,并且,与会者是尊重这种行为的.
> > > If the readers are not accustomed to - derogatory and ridiculous and discriminating against those HuaXia civilizations and Chinese symbol_Mandarin_Chinese character - the 慕mu洋yang犬quan们men -
> > > Please express your opinion in Chinese symbol_Mandarin_Chinese character in a loud and eager manner.
> > > I have observed a phenomenon. Why do people who speak on his behalf speak in his own language at many international conferences?
> > > After searching, I found the answer; that is the expression of the country that loves him and his nation and culture, and the participants respect this behavior.
> > 
> > 
> > Github is an academic community. The default language of communication is English. If you don't like English, you can go to CSDN or Zhihu .
> > > 为什么有些人总是看不惯自己的同胞使用自己母语来进行问题的讨论，我们承认有一些人在社区里发布垃圾言论但是只有中国会产生混蛋么？
> > > 我们抵触的只是以诋毁祖国文化来获取畸形的优越感的人。
> > > 你是个Easyboy？请收起你对着太平洋的屁股。
> > > Why do some people always hate their compatriots using their own language to discuss problems? We admit that some people post rubbish in the community but only China produces assholes?
> > > We are only against those who vilify the culture of their motherland in order to gain a distorted sense of superiority.

We should abide by the rules of github, which does not welcome anyone with verbal aggression.  if you can , please go to CSDN or Zhihu

**Comment by Develkone** [comment]
> > > 如果阅者访客看不惯-贬低和嘲讽和歧视我华夏文明与中文汉字汉语的那些慕洋犬们-的话,
> > > 请大声和踊跃地用中文汉字汉语发表自己的看法.
> > > 我观察到一个现象,为何在众多国际会议上,代表他那一国发言的人都是用他本国的语言?
> > > 经过搜索我找到的答案是;那是爱他的国和他的民族与文化的表现,并且,与会者是尊重这种行为的.
> > > If the readers are not accustomed to - derogatory and ridiculous and discriminating against those HuaXia civilizations and Chinese symbol_Mandarin_Chinese character - the 慕mu洋yang犬quan们men -
> > > Please express your opinion in Chinese symbol_Mandarin_Chinese character in a loud and eager manner.
> > > I have observed a phenomenon. Why do people who speak on his behalf speak in his own language at many international conferences?
> > > After searching, I found the answer; that is the expression of the country that loves him and his nation and culture, and the participants respect this behavior.
> > 
> > 
> > Github is an academic community. The default language of communication is English. If you don't like English, you can go to CSDN or Zhihu .
> > > 为什么有些人总是看不惯自己的同胞使用自己母语来进行问题的讨论，我们承认有一些人在社区里发布垃圾言论但是只有中国会产生混蛋么？
> > > 我们抵触的只是以诋毁祖国文化来获取畸形的优越感的人。
> > > 你是个Easyboy？请收起你对着太平洋的屁股。
> > > Why do some people always hate their compatriots using their own language to discuss problems? We admit that some people post rubbish in the community but only China produces assholes?
> > > We are only against those who vilify the culture of their motherland in order to gain a distorted sense of superiority.

https://www.zhihu.com/question/66642888,you can take a look at zhihu,look what qwas982 did and how does everyone think of his behavior.If you admit he is your compatriot,do as you like.

**Comment by V-GreenTea** [comment]
> 
> 
> > > > 如果阅者访客看不惯-贬低和嘲讽和歧视我华夏文明与中文汉字汉语的那些慕洋犬们-的话,
> > > > 请大声和踊跃地用中文汉字汉语发表自己的看法.
> > > > 我观察到一个现象,为何在众多国际会议上,代表他那一国发言的人都是用他本国的语言?
> > > > 经过搜索我找到的答案是;那是爱他的国和他的民族与文化的表现,并且,与会者是尊重这种行为的.
> > > > If the readers are not accustomed to - derogatory and ridiculous and discriminating against those HuaXia civilizations and Chinese symbol_Mandarin_Chinese character - the 慕mu洋yang犬quan们men -
> > > > Please express your opinion in Chinese symbol_Mandarin_Chinese character in a loud and eager manner.
> > > > I have observed a phenomenon. Why do people who speak on his behalf speak in his own language at many international conferences?
> > > > After searching, I found the answer; that is the expression of the country that loves him and his nation and culture, and the participants respect this behavior.
> > > 
> > > 
> > > Github is an academic community. The default language of communication is English. If you don't like English, you can go to CSDN or Zhihu .
> > > > 为什么有些人总是看不惯自己的同胞使用自己母语来进行问题的讨论，我们承认有一些人在社区里发布垃圾言论但是只有中国会产生混蛋么？
> > > > 我们抵触的只是以诋毁祖国文化来获取畸形的优越感的人。
> > > > 你是个Easyboy？请收起你对着太平洋的屁股。
> > > > Why do some people always hate their compatriots using their own language to discuss problems? We admit that some people post rubbish in the community but only China produces assholes?
> > > > We are only against those who vilify the culture of their motherland in order to gain a distorted sense of superiority.
> 
> https://www.zhihu.com/question/66642888.
> You can take a look at zhihu,look what qwas982 did and how does everyone think of his behavior.If you admit he is your compatriot,do as you like.

不是很懂慕洋犬们的脑子什么构造，用你妈和你爸教你的中文来表达就这么难？扯东扯西不明所以，直接说你们喜欢英文不就行了，低端的中文不配让你们这种高端人士使用。

**Comment by ZhuJiaYou** [comment]
GitHub is a international community, so we should use international language to communicate.
Only in this way, we can understand each other.
I think there must be some people blackening Chinese deliberately.

**Comment by liyishuai** [comment]
This thread has derailed from “handing issues” into endless off-topic personal attacks on “Chinese or no Chinese on GitHub”. I’d recommend freezing such non-contributive discussions and craft a multilingual announcement, unless we intentionally treat here as a dustbin for spammers.

**Comment by oldmud0** [comment]
I agree. It seems that the discussion has spun off into a moot debate about representation of Chinese people by using Chinese instead of English. As I don't see a clear resolution to that debate, I have hidden it to concentrate on the actual discussion about how to handle incoming noise.

However, I also see that the traffic is gradually declining back to normal levels:
![Analytics screenshot](https://user-images.githubusercontent.com/5247009/61885095-de6bb580-aec2-11e9-896d-09c3b4dc69ff.png)

So, maybe we should let go of the issue for now and add a section in `CONTRIBUTING.md` to address off-topic and humor issues, but nevertheless allow on-topic issues written in a language other than English.

**Comment by wopian** [comment]
Now that it's settled down, I think I'll go ahead and close this.

Most issues were locked for spam as they were low effort posts with only a title and an empty body (there were also some high-effort posts in Chinese/English that were closed and not locked).

This repository is the 69th most starred\[1] on GitHub and currently the 3rd highest trending repository on GitHub this week\[2]. 74 issues were created within 24 hours with just under 1,300 watchers\[3] - that's almost 95,000 emails sent by GitHub to watchers of this repository (74 for _each_ watcher). 

A further ~95,000 emails get sent each time they are closed (for humour, regardless of language, or for spam) while cleaning up the issues page so that all of the visitors finding this repository can see (and hopefully take part in) the serious effort currently being undertaken to make sure the code matches the scanned print outs of the source code exactly\[4].

\[1] https://github.com/search?p=7&q=stars%3A%3E40000&type=Repositories
\[2] https://github.com/trending?since=weekly
\[3] ![](https://badgen.net/github/watchers/chrislgarry/Apollo-11)
\[4] https://github.com/chrislgarry/Apollo-11/milestone/1
