### ISSUE TITLE
有些人总觉得别人丢脸，赶忙出来代表道歉，但实际上，在人家眼里，丢脸的是这种急哄哄道歉的人

### ISSUE THREAD

**Issue by Xmug** [chrislgarry/Apollo-11#488]

**Comment by ZsgsDesign** [comment]
Please do not abuse Issues.

**Comment by haixiang245** [comment]
CCP please enhance the GFW further, tkx.

**Comment by jhy1234** [comment]
What's your problem? Please do not abuse Issues.

**Comment by linfili** [comment]
It's a shameful thing for the way you are using "Issues".

**Comment by charming7201** [comment]
不就是灌水多了点，issue不就是这么玩的（滑稽）

**Comment by cyp0633** [comment]
> 不就是灌水多了点，issue不就是这么玩的（滑稽）

个人认为，灌水也应该先close掉，而且这么多确实影响正经阅读了

**Comment by charming7201** [comment]
> 
> 
> > 不就是灌水多了点，issue不就是这么玩的（滑稽）
> 
> 个人认为，灌水也应该先close掉，而且这么多确实影响正经阅读了

毕竟这是排行榜第一，人多点儿正常

**Comment by NianhengWu** [comment]
Who told you this is the way of using 'issue'?! If you want to start a fight, do it on Chinese crappy social platform like Weibo. We want to see real discussion here, not stupid flaming.

谁跟你说Issue就是这么用的，你要是想骂人在微博这种中国垃圾社交网络上去骂。我们在这是看认真讨论的，不是泼妇骂街。

**Comment by NanamiArihara** [comment]
你📖的都怼，，，你📖啥就是啥不狡辩，，，

**Comment by Rinacm** [comment]
然而敢于站出来道歉的至少有那个勇气，你在这里拥护那群灌水的废物是什么意思呢？

**Comment by egdw** [comment]
请不要在出来丢中国人的脸了谢谢.
