### ISSUE TITLE
我也是review过阿波罗11号登月项目源码的人了啊！！！激动 哈哈  有点飘了😄

### ISSUE THREAD

**Issue by walkermanx** [chrislgarry/Apollo-11#499]
是不是review完这个源码   我就能走上人生巅峰了？

**Comment by liyujiang-gzu** [comment]
兄弟，这两天凑热闹的中国人真多，又双叒叕霸榜了

**Comment by yichunl** [comment]
兄弟微信文章看过没: https://mp.weixin.qq.com/s/sP087NBWPw9BWf2oJKuxLw
pls stop abusing issue
