### ISSUE TITLE
Original lead author not credited in README

### ISSUE THREAD

**Issue by gp** [chrislgarry/Apollo-11#5]

**Comment by chrislgarry** [comment]
I will compile a list of the original AGC developers, as well as the folks at MIT who scanned the paper source, and those who digitized the scans. If you have compiled a list already, please send my way. Thanks.

**Comment by thomblake** [comment]
Margaret Hamilton was the lead of the software development team at MIT, but the names of the rest of her team seem hard to track down.  This doc is probably the best resource to see the various folks involved in the project: http://klabs.org/history/history_docs/mit_docs/1711.pdf

**Comment by Hunter-Github** [comment]
Well, Ron Burkey ([Virtual AGC](http://www.ibiblio.org/apollo/links.html)) isn't credited in the README either.

**Comment by onmyway133** [comment]
@chrislgarry this is interesting. But where do you get it from? I can't seem to find the LICENSE. I thought NASA should opened the this source code at https://code.nasa.gov/#/

**Comment by michax** [comment]
It would be nice to put source used. Seems like direct clone of:
https://code.google.com/archive/p/virtualagc/source/default/source

**Comment by michax** [comment]
Would be also cool if you copy wiki from code.google to github. 
https://code.google.com/archive/p/virtualagc/wikis

**Comment by fragglebob** [comment]
@michax the wiki is here https://github.com/rburkey2005/virtualagc/tree/wiki

**Comment by chrislgarry** [comment]
@onmyway133 there is almost no difference. I changed the extensions from .agc to .s for syntax highlighting, but that's about it. AFAIK, Virtual AGC project is the only source for original Apollo 11 source in digital form, as they put in quite some effort to work with MIT to digitize it for their AGC emulator. I'm currently talking with Ron, the project owner, about attribution. Stay tuned. @michax this repository is only a clone of the Apollo 11 source code they digitized, not Virtual AGC, although it is a super cool project and I highly suggest checking it out. They designed Virtual AGC to directly execute original Apollo 11 assembly which is quite impressive.

**Comment by oznogon** [comment]
Hamilton, Lickly, Martin, Sears, Battin, Hoag, and Ragan are cited in [CONTRACT_AND_APPROVALS.s](https://github.com/chrislgarry/Apollo-11/blob/master/CONTRACT_AND_APPROVALS.s).

Other authors are noted in the [MOD lines of each file's code](https://github.com/chrislgarry/Apollo-11/search?utf8=%E2%9C%93&q=%22%23+MOD%22&type=Code).

**Comment by rtoal** [comment]
Anyone know how to contact Hamilton? If she's not already on GitHub, it'd be great to see her upload some of her stuff here.

**Comment by chrislgarry** [comment]
Attributions updated.
