### ISSUE TITLE
终于参加了一个nb的项目了，膨胀了

### ISSUE THREAD

**Issue by quhaojieame** [chrislgarry/Apollo-11#504]

**Comment by qq1037861239** [comment]
很快就会有些傻逼骂你了，搞得好像是他爸的项目一样

**Comment by dangyanglim** [comment]
@qq1037861239 对的，开玩笑而已，那些人太紧张了

**Comment by linfili** [comment]
> @qq1037861239 对的，开玩笑而已，那些人太紧张了

别丢人现眼了！在这里刷什么存在感，先去看看GitHub的issue是干什么用的行不行？
瞎提issue要所有关注这个项目的人都浪费精力看你的没有建设意见的口水灌水贴？
