### ISSUE TITLE
这代码谁看的懂，敬畏...

### ISSUE THREAD

**Issue by veasion** [chrislgarry/Apollo-11#519]

**Comment by qwas982** [comment]
那个年代c语言还没诞生呢.甚至x86和arm都没诞生,因此用的汇编自然也不是x86汇编和arm汇编.
这是一种专用的硬件(专门设计的电路)和专门为这种硬件设计的语言,算法是直接用数学方程式先写在纸上的,然后再由汇编工程师当人肉编译器翻译为这种专用电路可执行的汇编代码.
