### ISSUE TITLE
Missing Dockerfile

### ISSUE THREAD

**Issue by brouberol** [chrislgarry/Apollo-11#52]
Hi,

I'd like to be able to land apollo-11 on my dev machine, or even autoscale it in production. Docker would really help with that. What would it take to run Apollo-11 in a container?

**Comment by rumpelsepp** [comment]
Lol

**Comment by pawel-dubiel** [comment]
Hello, It doesn't accurately answer your problem, but you can land Apollo 11 on your dev machine http://nassp.sourceforge.net/wiki/Main_Page . It supports AGC software.
