### ISSUE TITLE
How to run this code

### ISSUE THREAD

**Issue by yanzhao77** [chrislgarry/Apollo-11#523]
These codes can be opened in visual Studio, but cannot run

**Comment by wangrunbo** [comment]
You need to buy a spaceship on amazon first

**Comment by surifans** [comment]
you should this,and do this ,then do this ,then it can run~

**Comment by surifans** [comment]
you should do this,and do that ,then do this ,then it can run~

**Comment by surifans** [comment]
你先这样，再这样，再那样，明白了吧，最后就可以跑了～

**Comment by oldmud0** [comment]
I recommend an IBM System/360.

**Comment by wonghumen** [comment]
www.taobao.com price:$1024 free shipping
