### ISSUE TITLE
用汇编语言写的？我需要买一台阿波罗号飞船运行此代码，请哪里可以买到阿波罗号

### ISSUE THREAD

**Issue by richardgong1987** [chrislgarry/Apollo-11#524]
用汇编语言写的？我需要买一台阿波罗号飞船运行此代码，请问哪里可以买到

**Comment by larack8** [comment]
I have someone for sell. If you would like to buy , please contact me secretly!

**Comment by curse-zhina** [comment]
去你妈逼里领

**Comment by wonghumen** [comment]
> 用汇编语言写的？我需要买一台阿波罗号飞船运行此代码，请问哪里可以买到

mark

**Comment by dcy0701** [comment]
买一艘把你妈骨灰送上天
