### ISSUE TITLE
Extension pack for picking up Matt Damon

### ISSUE THREAD

**Issue by ghost** [chrislgarry/Apollo-11#53]
I've sent a pull request for an extension to pick up Matt Damon. Please review ASAP: https://github.com/chrislgarry/Apollo-11/pull/54

**Comment by jrroop** [comment]
I suggest leveraging the MATTDAEMON (Multipurpose Astronaut Temporary Transportation). That would address other issues (Such as for Major Tom and Astronaut Taylor.

**Comment by badvision** [comment]
Congress didn't approve the budget.  Suggest he learns to grow wings instead.   Wait, are you filming this conversation?

**Comment by thesandbender** [comment]
All, this has been resolved.  Please as <a href="https://twitter.com/SarahKSilverman">Sarah Silverman</a> to merge the patch.  Oh, wait, that was something different.  Please disregard.

**Comment by nuuman** [comment]
@chrislgarry INVALID?!? Expect an angry Ben Affleck on your door any minute.

**Comment by Tropicalrambler** [comment]
I wonder if you would like them apples.

**Comment by chrislgarry** [comment]
Considering Matt Damon attempted to maroon the entire Interstellar crew, he can stay on Mars.

**Comment by RexRowan** [comment]
Give him long enough time, he will mutate and adapt to the environment.

**Comment by IronJaeger** [comment]
@RexRowan then the Marsians will send him to explore Earth and leave him here, when the planet will be ruled by apes, and he have to believe in darwin's theory and reverse-engeneer his dna to back then

**Comment by mrmattdamon** [comment]
> Considering Matt Damon attempted to maroon the entire Endurance crew (Interstellar), he can stay on Mars.

Fuck

**Comment by dwanderton** [comment]
😁 I think i speak for many when i say this just made my day! +1 please reopen

**Comment by jayjaybillings** [comment]
Closed? Well, apologies to Matt Damon but we ran out of time.

**Comment by hemanth** [comment]
![](https://media.giphy.com/media/xnXcMMNDpQF4k/giphy.gif)

**Comment by chrislgarry** [comment]
Reopening to reflect that Matt Damon is indeed still on Mars.

**Comment by LuisAlejandro** [comment]
This bug has been hijacked by Jimmy Kimmel.

**Comment by Qurmo** [comment]
What happened to, we leave no man behind? ;).
