### ISSUE TITLE
added bangla language contribution

### ISSUE THREAD

**Issue by sabbirshawon** [chrislgarry/Apollo-11#543]
I had added Bangla language contribution one month ago but it still not added. Can @chrislgarry  Add this from the checkout pull request?

**Comment by wopian** [comment]
I'm going through the PRs from oldest to newest, with priority to proofing PRs which I unfortunately got quite behind on over the summer. 

I've been slowly catching up and been looking around for native users to review the translation PRs (we got a huge amount over the summer) for the past few months, so they will be reviewed and merged in due time. :+1:

**Comment by sabbirshawon** [comment]
thanks for reply @wopian
