### ISSUE TITLE
[Tutorial] Well ... :)

### ISSUE THREAD

**Issue by rubyFeedback** [chrislgarry/Apollo-11#557]
This may be a bit much to ask, because people don't have much time available, I suppose ...

... but I think I am not the only one who thinks that it would be nice if someone could explain the code too.

This does NOT have to be to every minute details, mind you; just a single high quality document perhaps that introduces to the essentials, sort of like a semi-detailed overview, and linked in from the main README.md. (Sorry if I write this in the wrong github repository; I don't know who is running what really ... I am only interested in reading some explanations how these things did work. Makes watching these old videos more fun too!)

**Comment by wopian** [comment]
You may be interested in the Space Guidance Analysis (SGA) memos:

http://www.ibiblio.org/apollo/links.html#Space_Guidance_Analysis_SGA_memos

And the User's Guide (by the same people who wrote the code) for what each subroutine does:

http://www.ibiblio.org/apollo/Documents/j2-80-E-2448-REV1_text.pdf
http://www.ibiblio.org/apollo/NARA-SW/SkylabDataCards.pdf
