### ISSUE TITLE
DOWNLINK_LISTS.s +233 Space instead of Tab

### ISSUE THREAD

**Issue by nobswolf** [chrislgarry/Apollo-11#56]
I just did some automatic checking without any real understanding so far, but:

Is this Space between 2DNADR and TCDH correct? It looks like it should be a Tab.

**Comment by nobswolf** [comment]
similar:

ASCENT_GUIDANCE.s:567:		BANK 27
P51-P53.s:249:		OCT 405
LUNAR_LANDING_GUIDANCE_EQUATIONS.s:136:  		READ CHAN30
KALCMANU_STEERING.s:244:		SETLOC MANUSTUF
P34-35_P74-75.s:965:		SETLOC P30SUBS
INTERPRETER.s:1307:		TC OVERFLWY

**Comment by MooglyGuy** [comment]
Does it matter?

**Comment by chrislgarry** [comment]
If you think there is an issue and you know the fix, please submit a PR. Thanks.
