### ISSUE TITLE
Proof ALARM_AND_ABORT

### ISSUE THREAD

**Issue by wopian** [chrislgarry/Apollo-11#564]
Proof read transcribed code of [ALARM_AND_ABORT](//github.com/chrislgarry/Apollo-11/blob/master/Luminary099/ALARM_AND_ABORT.agc) against scans

Lines: 251
Page: 1381—1385 (4)

Reduced quality scans can be found [here][1]

[1]://ibiblio.org/apollo/ScansForConversion/Luminary099

**Comment by cvsmith** [comment]
I've added fixes for this file in this PR: https://github.com/chrislgarry/Apollo-11/pull/682
