### ISSUE TITLE
Proof DAPIDLER_PROGRAM

### ISSUE THREAD

**Issue by wopian** [chrislgarry/Apollo-11#573]
Proof read transcribed code of [DAPIDLER_PROGRAM](//github.com/chrislgarry/Apollo-11/blob/master/Luminary099/DAPIDLER_PROGRAM.agc) against scans

Lines: 481
Page: 1410—1420 (10)

Reduced quality scans can be found [here][1]

[1]://ibiblio.org/apollo/ScansForConversion/Luminary099

**Comment by cnsumner** [comment]
Working on this one.

**Comment by cnsumner** [comment]
Question on this: on the larger multiline comments, should I be spacing everything exactly like the scans, aligning things with the line above just like in the scan, or should I be following the conventions in the contributing readme?  For example, there are situations where I would need to use a tab and then 5 spaces to line something up just the scan shows, but the contributing document says to use only tabs for indentation (and then in another place it says to use 3 spaces for indentation...).

Also there are numerous places where there is a word with a colon after it, then 2 spaces, then more words. Should I keep the 2 spaces or reduce it to 1?

I looked around at other merged PRs and I'm seeing some people faithfully reproducing the scan's alignment, and others changing it to match the contributing document's conventions.

**Comment by cnsumner** [comment]
Created a PR with all pages proofed. The largest areas mentioned above that are in question start at line numbers 214 and 332 respectively.

**Comment by wopian** [comment]
> should I be spacing everything exactly like the scans, aligning things with the line above just like in the scan, or should I be following the conventions in the contributing readme? For example, there are situations where I would need to use a tab and then 5 spaces to line something up just the scan shows, but the contributing document says to use only tabs for indentation (and then in another place it says to use 3 spaces for indentation...).

Comments without code (e.g [page 1414](https://www.ibiblio.org/apollo/ScansForConversion/Luminary099/1414.jpg)) should be on the left

![image](https://user-images.githubusercontent.com/3440094/95615423-1f1c0400-0a60-11eb-90b6-85bfe0c1bb8d.png)

![image](https://user-images.githubusercontent.com/3440094/95615469-33600100-0a60-11eb-9109-f60913f44764.png)

> but the contributing document says to use only tabs for indentation (and then in another place it says to use 3 spaces for indentation...).

The files use tabs, but sometimes needs spaces to match what was written (e.g sometimes a double or triple space occurs that can't be done with the tab columns.

> Also there are numerous places where there is a word with a colon after it, then 2 spaces, then more words. Should I keep the 2 spaces or reduce it to 1?

Whatever the scans use. If the scans has:

- 1 space after the colon, use 1 space
- 2 spaces after the colon, use 2
- 1 space after the colon, but the file has 2 spaces, use 1 space

> I looked around at other merged PRs and I'm seeing some people faithfully reproducing the scan's alignment, and others changing it to match the contributing document's conventions.

The CONTRIBUTING convention is to match the scans<sup>[1](https://github.com/chrislgarry/Apollo-11/blob/master/CONTRIBUTING.md#note), [2](https://github.com/chrislgarry/Apollo-11/blob/master/CONTRIBUTING.md#contributing)</sup>. The wording on the spacing section probably isn't the best - the example used had 2 spaces in the scans but 1 in the digitisation at the time (but doesn't actually source the scan/file used in example). Most of the time (but not always) the scans have a double space, which is why it was included.

I will update the CONTRIBUTING document to make the distinctions clearer instead of sounding like a steadfast rule 👍

**Comment by cnsumner** [comment]
Ok, thank you for the clarifications, much appreciated.  I believe all of the changes I have made are correct then, according to what you've said.
