### ISSUE TITLE
Proof DAP_INTERFACE_SUBROUTINES

### ISSUE THREAD

**Issue by wopian** [chrislgarry/Apollo-11#574]
Proof read transcribed code of [DAP_INTERFACE_SUBROUTINES](//github.com/chrislgarry/Apollo-11/blob/master/Luminary099/DAP_INTERFACE_SUBROUTINES.agc) against scans

Lines: 176
Page: 1406—1409 (4)

Reduced quality scans can be found [here][1]

[1]://ibiblio.org/apollo/ScansForConversion/Luminary099

**Comment by cvsmith** [comment]
https://github.com/chrislgarry/Apollo-11/pull/683
