### ISSUE TITLE
README lacking explanation

### ISSUE THREAD

**Issue by wmhilton** [chrislgarry/Apollo-11#59]
Stumbled across this via Twitter. I see all the recent issues/pull requests are jokes but what is this actually? The README file mentions "Virtual AGC and MIT" but there's no links. I've never even heard of a .s file before. Does MIT have an Apollo emulator or something?

**Comment by indy91** [comment]
MIT wrote this code for the Apollo program. It first became available in digital form many years ago thanks to Ronald Burkey, who created an AGC emulator called Virtual AGC. Here the relevant website: www.ibiblio.org/apollo

**Comment by muellermartin** [comment]
I also came here via Twitter and [Hacker News](https://news.ycombinator.com/item?id=12048945), too. Maybe the comments on the latter source can help clear up some uncertainities.
To adress your questions:
- Virtual AGC might refer to this project: http://www.ibiblio.org/apollo/ ("computer simulation of the onboard guidance computers used in the Apollo Program's lunar missions")
- `.s` files usually are assembler files. The README states it's used by the `yaYUL` assembler. There seems to be [some information on the Virtual AGC website](http://www.ibiblio.org/apollo/yaYUL.html#AGC4_Assembly_Language).

**Comment by MooglyGuy** [comment]
No offense, but if you are unfamiliar enough with assembly language programming that you don't know what a .s file is, then maybe this github project isn't really your speed.

**Comment by chrislgarry** [comment]
I've updated the README. Please let me know if this helps.

**Comment by wmhilton** [comment]
Awesome! Much clearer now. Definitely think that helps!
