### ISSUE TITLE
Proof INFLIGHT_ALIGNMENT_ROUTINES

### ISSUE THREAD

**Issue by wopian** [chrislgarry/Apollo-11#591]
Proof read transcribed code of [INFLIGHT_ALIGNMENT_ROUTINES](//github.com/chrislgarry/Apollo-11/blob/master/Luminary099/INFLIGHT_ALIGNMENT_ROUTINES.agc) against scans

Lines: 300
Page: 1249—1258 (9)

Reduced quality scans can be found [here][1]

[1]://ibiblio.org/apollo/ScansForConversion/Luminary099

**Comment by jstuyck** [comment]
Reviewed. #673
