### ISSUE TITLE
Proof INPUT_OUTPUT_CHANNEL_BIT_DESCRIPTIONS

### ISSUE THREAD

**Issue by wopian** [chrislgarry/Apollo-11#592]
Proof read transcribed code of [INPUT_OUTPUT_CHANNEL_BIT_DESCRIPTIONS](//github.com/chrislgarry/Apollo-11/blob/master/Luminary099/INPUT_OUTPUT_CHANNEL_BIT_DESCRIPTIONS.agc) against scans

Lines: 224
Page: 0054—0060 (7)

Reduced quality scans can be found [here][1]

[1]://ibiblio.org/apollo/ScansForConversion/Luminary099

**Comment by panoreak** [comment]
Hello! Can I work on this? 😄

**Comment by wopian** [comment]
> @panoreak: Hello! Can I work on this? 😄

Go ahead! Read [CONTRIBUTING.md](https://github.com/chrislgarry/Apollo-11/blob/master/CONTRIBUTING.md) before starting 👍

**Comment by panoreak** [comment]
> > @panoreak: Hello! Can I work on this? 😄
> 
> Go ahead! Read [CONTRIBUTING.md](https://github.com/chrislgarry/Apollo-11/blob/master/CONTRIBUTING.md) before starting 👍

Thank you! I'll make sure to read the guidelines 😊
