### ISSUE TITLE
Proof INTERRUPT_LEAD_INS

### ISSUE THREAD

**Issue by wopian** [chrislgarry/Apollo-11#597]
Proof read transcribed code of [INTERRUPT_LEAD_INS](//github.com/chrislgarry/Apollo-11/blob/master/Luminary099/INTERRUPT_LEAD_INS.agc) against scans

Lines: 117
Page: 0153—0154 (2)

Reduced quality scans can be found [here][1]

[1]://ibiblio.org/apollo/ScansForConversion/Luminary099

**Comment by Nabeelhassan** [comment]
I am taking this task. Will create a pull request shortly.

**Comment by Nabeelhassan** [comment]
why did you remove the hacktoberfest label @wopian ???

**Comment by wopian** [comment]
> why did you remove the hacktoberfest label @wopian ???

Because it's a tag temporarily added alongside `Help Wanted` (all open issues) and `Good First Issue` (on issues with `Help Wanted` and either `Tiny` or `Small` labels). 

These labels are there to guide visitors to issues they will manage to complete, instead of going in blind to a huge or bigger issue with 40+ pages and getting overwhelmed. The two biggest size labels are not something that can be reasonably proofed and reviewed within a month and do not have `Good First Issue` or `hacktoberfest` labels.

This issue now has a PR that proofs it and no longer needs the `Helped Wanted` label. The (lack of) `hacktoberfest` label has no effect on Hacktoberfest eligibility as the repository has the `hacktoberfest` topic and **all** merged PRs are eligble.

**Comment by Nabeelhassan** [comment]
Ok, thanks for the clarification.
