### ISSUE TITLE
Proof KALCMANU_STEERING

### ISSUE THREAD

**Issue by wopian** [chrislgarry/Apollo-11#598]
Proof read transcribed code of [KALCMANU_STEERING](//github.com/chrislgarry/Apollo-11/blob/master/Luminary099/KALCMANU_STEERING.agc) against scans

Lines: 229
Page: 0365—0369 (5)

Reduced quality scans can be found [here][1]

[1]://ibiblio.org/apollo/ScansForConversion/Luminary099

**Comment by kagof** [comment]
I wouldn't mind grabbing this, if it is available!
