### ISSUE TITLE
Proof KALMAN_FILTER

### ISSUE THREAD

**Issue by wopian** [chrislgarry/Apollo-11#599]
Proof read transcribed code of [KALMAN_FILTER](//github.com/chrislgarry/Apollo-11/blob/master/Luminary099/KALMAN_FILTER.agc) against scans

Lines: 101
Page: 1470—1471 (2)

Reduced quality scans can be found [here][1]

[1]://ibiblio.org/apollo/ScansForConversion/Luminary099

**Comment by eldan-dex** [comment]
Verified the file to be correct, no edits are needed.
