### ISSUE TITLE
Proof KEYRUPT_UPRUPT

### ISSUE THREAD

**Issue by wopian** [chrislgarry/Apollo-11#600]
Proof read transcribed code of [KEYRUPT_UPRUPT](//github.com/chrislgarry/Apollo-11/blob/master/Luminary099/KEYRUPT_UPRUPT.agc) against scans

Lines: 132
Page: 1338—1340 (3)

Reduced quality scans can be found [here][1]

[1]://ibiblio.org/apollo/ScansForConversion/Luminary099

**Comment by crhaugen** [comment]
Hey, I'll take a look at this If that's alright :)
