### ISSUE TITLE
Proof LAMBERT_AIMPOINT_GUIDANCE

### ISSUE THREAD

**Issue by wopian** [chrislgarry/Apollo-11#601]
Proof read transcribed code of [LAMBERT_AIMPOINT_GUIDANCE](//github.com/chrislgarry/Apollo-11/blob/master/Luminary099/LAMBERT_AIMPOINT_GUIDANCE.agc) against scans

Lines: 169
Page: 0651—0653 (3)

Reduced quality scans can be found [here][1]

[1]://ibiblio.org/apollo/ScansForConversion/Luminary099

**Comment by travis8** [comment]
I'd like to take this one please.
