### ISSUE TITLE
Proof LATITUDE_LONGITUDE_SUBROUTINES

### ISSUE THREAD

**Issue by wopian** [chrislgarry/Apollo-11#603]
Proof read transcribed code of [LATITUDE_LONGITUDE_SUBROUTINES](//github.com/chrislgarry/Apollo-11/blob/master/Luminary099/LATITUDE_LONGITUDE_SUBROUTINES.agc) against scans

Lines: 308
Page: 1133—1139 (6)

Reduced quality scans can be found [here][1]

[1]://ibiblio.org/apollo/ScansForConversion/Luminary099

**Comment by jcyktor** [comment]
I can take this.
