### ISSUE TITLE
Proof LEM_GEOMETRY

### ISSUE THREAD

**Issue by wopian** [chrislgarry/Apollo-11#604]
Proof read transcribed code of [LEM_GEOMETRY](//github.com/chrislgarry/Apollo-11/blob/master/Luminary099/LEM_GEOMETRY.agc) against scans

Lines: 209
Page: 0320—0325 (6)

Reduced quality scans can be found [here][1]

[1]://ibiblio.org/apollo/ScansForConversion/Luminary099

**Comment by GintasS** [comment]
I'm going to take it.

**Comment by GintasS** [comment]
https://github.com/chrislgarry/Apollo-11/pull/725

**Comment by GintasS** [comment]
Thanks!
