### ISSUE TITLE
Proof LUNAR_AND_SOLAR_EPHEMERIDES_SUBROUTINES

### ISSUE THREAD

**Issue by wopian** [chrislgarry/Apollo-11#605]
Proof read transcribed code of [LUNAR_AND_SOLAR_EPHEMERIDES_SUBROUTINES](//github.com/chrislgarry/Apollo-11/blob/master/Luminary099/LUNAR_AND_SOLAR_EPHEMERIDES_SUBROUTINES.agc) against scans

Lines: 196
Page: 0984—0987 (4)

Reduced quality scans can be found [here][1]

[1]://ibiblio.org/apollo/ScansForConversion/Luminary099

**Comment by rnd-debug** [comment]
Hi. I would like to try my chance against this part (before eventually proceeding with a bigger part) (at least I have already found an issue here :)
