### ISSUE TITLE
Proof RCS_FAILURE_MONITOR

### ISSUE THREAD

**Issue by wopian** [chrislgarry/Apollo-11#631]
Proof read transcribed code of [RCS_FAILURE_MONITOR](//github.com/chrislgarry/Apollo-11/blob/master/Luminary099/RCS_FAILURE_MONITOR.agc) against scans

Lines: 173
Page: 0190—0192 (3)

Reduced quality scans can be found [here][1]

[1]://ibiblio.org/apollo/ScansForConversion/Luminary099

**Comment by h4llow3En** [comment]
I will take a look at this

**Comment by sidemt** [comment]
May I take this one?

**Comment by wopian** [comment]
@sidemt go ahead! 👍

**Comment by sidemt** [comment]
@wopian Sorry I just realized there already is another pull request to this issue. Did I check a wrong one?
