### ISSUE TITLE
Proof RESTARTS_ROUTINE

### ISSUE THREAD

**Issue by wopian** [chrislgarry/Apollo-11#632]
Proof read transcribed code of [RESTARTS_ROUTINE](//github.com/chrislgarry/Apollo-11/blob/master/Luminary099/RESTARTS_ROUTINE.agc) against scans

Lines: 325
Page: 1303—1309 (6)

Reduced quality scans can be found [here][1]

[1]://ibiblio.org/apollo/ScansForConversion/Luminary099

**Comment by crhaugen** [comment]
Hey, I'd like to tackle this issue!
