### ISSUE TITLE
Proof RESTART_TABLES

### ISSUE THREAD

**Issue by wopian** [chrislgarry/Apollo-11#633]
Proof read transcribed code of [RESTART_TABLES](//github.com/chrislgarry/Apollo-11/blob/master/Luminary099/RESTART_TABLES.agc) against scans

Lines: 297
Page: 0238—0243 (5)

Reduced quality scans can be found [here][1]

[1]://ibiblio.org/apollo/ScansForConversion/Luminary099

**Comment by RichardPilbery** [comment]
I'd like to tackle this issue.

**Comment by RichardPilbery** [comment]
Okay I've made a start with this but need some advice about the tables themselves. Page 239 has a number of columns that precede the columns included in RESTART_TABLES.agc.

For example, line A0079 on page 239 is:

REF 29 LAST 213. 0074. then a couple of columns then EBANK- STATE

Should these be included?
