### ISSUE TITLE
Proof SINGLE_PRECISION_SUBROUTINES

### ISSUE THREAD

**Issue by wopian** [chrislgarry/Apollo-11#638]
Proof read transcribed code of [SINGLE_PRECISION_SUBROUTINES](//github.com/chrislgarry/Apollo-11/blob/master/Luminary099/SINGLE_PRECISION_SUBROUTINES.agc) against scans

Lines: 69
Page: 1102

Reduced quality scans can be found [here][1]

[1]://ibiblio.org/apollo/ScansForConversion/Luminary099

**Comment by GannonTdW** [comment]
#657 
One extra point at the end of the last comment
