### ISSUE TITLE
Proof SYSTEM_TEST_STANDARD_LEAD_INS

### ISSUE THREAD

**Issue by wopian** [chrislgarry/Apollo-11#641]
Proof read transcribed code of [SYSTEM_TEST_STANDARD_LEAD_INS](//github.com/chrislgarry/Apollo-11/blob/master/Luminary099/SYSTEM_TEST_STANDARD_LEAD_INS.agc) against scans

Lines: 125
Page: 0370—0372 (3)

Reduced quality scans can be found [here][1]

[1]://ibiblio.org/apollo/ScansForConversion/Luminary099

**Comment by mapra99** [comment]
Hi! @wopian. I'm new here, can I work on this issue?

**Comment by wopian** [comment]
> Hi! @wopian. I'm new here, can I work on this issue?

Go ahead! 👍

**Comment by mapra99** [comment]
Ok, thanks @wopian :)
I have this question
1. On page 370 we have these lines I'm highlighting
![image](https://user-images.githubusercontent.com/27536621/80318366-4db66300-87cf-11ea-922f-7d5902e9ed30.png)

This is the corresponding transcription.
https://github.com/chrislgarry/Apollo-11/blob/47d20df7df55d78939ecf5a7cab14a10d1484d83/Luminary099/SYSTEM_TEST_STANDARD_LEAD_INS.agc#L64-L66

There a tab between `EBUF2` and `+1`, and the same for `0` and `-1`. Is this ok or should I replace this tab with a space?

Same thing happens in page 372 for these lines
![image](https://user-images.githubusercontent.com/27536621/80318456-e0570200-87cf-11ea-8160-706b1144900a.png)

https://github.com/chrislgarry/Apollo-11/blob/47d20df7df55d78939ecf5a7cab14a10d1484d83/Luminary099/SYSTEM_TEST_STANDARD_LEAD_INS.agc#L95-L97

**Comment by wopian** [comment]
> There a tab between `EBUF2` and `+1`, and the same for `0` and `-1`. Is this ok or should I replace this tab with a space?

These are different columns in the printouts. Make sure you read https://github.com/chrislgarry/Apollo-11/blob/master/CONTRIBUTING.md#formatting - the GitHub previews don't always display tabs 8 spaces wide, it should look like the following in your editor:

![image](https://user-images.githubusercontent.com/3440094/80322889-d0670e80-881f-11ea-9e9a-4bda82b6810d.png)

**Comment by mapra99** [comment]
Ok! I opened #667 fo this issue
