### ISSUE TITLE
Proof TAGS_FOR_RELATIVE_SETLOC

### ISSUE THREAD

**Issue by wopian** [chrislgarry/Apollo-11#644]
Proof read transcribed code of [TAGS_FOR_RELATIVE_SETLOC](//github.com/chrislgarry/Apollo-11/blob/master/Luminary099/TAGS_FOR_RELATIVE_SETLOC.agc) against scans

Lines: 347
Page: 0028—0037 (9)

Reduced quality scans can be found [here][1]

[1]://ibiblio.org/apollo/ScansForConversion/Luminary099

**Comment by EGA-SUPREMO** [comment]
I only checked for typos using both reduced quality scans and the high ones and I didn't find any differences.
