### ISSUE TITLE
Proof THE_LUNAR_LANDING

### ISSUE THREAD

**Issue by wopian** [chrislgarry/Apollo-11#645]
Proof read transcribed code of [THE_LUNAR_LANDING](//github.com/chrislgarry/Apollo-11/blob/master/Luminary099/THE_LUNAR_LANDING.agc) against scans

Lines: 335
Page: 0785—0792 (7)

Reduced quality scans can be found [here][1]

[1]://ibiblio.org/apollo/ScansForConversion/Luminary099

**Comment by cetfor** [comment]
Issue 1: `GOTOP00H` should be `GOTOPOOH` ([code](https://github.com/chrislgarry/Apollo-11/blob/master/Luminary099/THE_LUNAR_LANDING.agc#L248), [img](http://www.ibiblio.org/apollo/ScansForConversion/Luminary099/0789.jpg))

Issue 2: `GOTOP00H` should be `GOTOPOOH` ([code](https://github.com/chrislgarry/Apollo-11/blob/master/Luminary099/THE_LUNAR_LANDING.agc#L320), [img](http://www.ibiblio.org/apollo/ScansForConversion/Luminary099/0791.jpg))

Issue 3:  `GOTOP00H` should be `GOTOPOOH` ([code](https://github.com/chrislgarry/Apollo-11/blob/master/Luminary099/THE_LUNAR_LANDING.agc#L332), [img](http://www.ibiblio.org/apollo/ScansForConversion/Luminary099/0792.jpg))

These are the only issues I was able to find.  The comments in this one were fun to read.  Some of the images were pretty rough in areas but nothing else stood out as an issue.

**Comment by wopian** [comment]
Yeah, the print quality of the Luminary printouts are considerably worse than Comanche (but not the worst from the Apollo program - Colossus249 is even harder to read)
