### ISSUE TITLE
Proof TRIM_GIMBAL_CNTROL_SYSTEM

### ISSUE THREAD

**Issue by wopian** [chrislgarry/Apollo-11#649]
Proof read transcribed code of [TRIM_GIMBAL_CNTROL_SYSTEM](//github.com/chrislgarry/Apollo-11/blob/master/Luminary099/TRIM_GIMBAL_CNTROL_SYSTEM.agc) against scans

Lines: 622
Page: 1472—1485 (13)

Reduced quality scans can be found [here][1]

[1]://ibiblio.org/apollo/ScansForConversion/Luminary099

**Comment by zpeters** [comment]
I would like to give this a go

**Comment by zpeters** [comment]
Review completed.  No discrepancies or issues.

**Comment by wopian** [comment]
Typo in file name

![image](https://user-images.githubusercontent.com/3440094/95278995-7300d000-0849-11eb-928c-a587d8d0a24f.png)

**Comment by wopian** [comment]
There's some discrepancies with some equations in the comments, like [line 136 ](https://github.com/chrislgarry/Apollo-11/blob/master/Luminary099/TRIM_GIMBAL_CNTROL_SYSTEM.agc#L136)

![image](https://user-images.githubusercontent.com/3440094/95279558-eb1bc580-084a-11eb-9f89-d82e827341c1.png)

**Comment by zpeters** [comment]
Thank you for pointing this out.  Will start looking at file names in addition to the other things I missed.

**Comment by zpeters** [comment]
i just realized that i failed to read CONTRIBUTING.md.  Going to make sure and read this over.   Thanks again for the feedback.  This is a really fun project

**Comment by zpeters** [comment]
> Typo in file name (`CNTROL` instead of `CONTROL`)
> 
> ![image](https://user-images.githubusercontent.com/3440094/95278995-7300d000-0849-11eb-928c-a587d8d0a24f.png)

Could you point me to where this is located? Just curious where i need to look to confirm the correct file name.  Thanks

**Comment by wopian** [comment]
> > Typo in file name (`CNTROL` instead of `CONTROL`)
> > ![image](https://user-images.githubusercontent.com/3440094/95278995-7300d000-0849-11eb-928c-a587d8d0a24f.png)
> 
> Could you point me to where this is located? Just curious where i need to look to confirm the correct file name. Thanks

First scanned page of each file (before `0001`/`R0001`) - https://www.ibiblio.org/apollo/ScansForConversion/Luminary099/1472.jpg

**Comment by zpeters** [comment]
added pr #756 hopefully everything looks okay
