### ISSUE TITLE
Python fork

### ISSUE THREAD

**Issue by Tropicalrambler** [chrislgarry/Apollo-11#67]
I hereby request help with creating a Python fork to run this on a Raspberry Pi 2...  Maybe a Raspberry Pi 3.

**Comment by pedromorgan** [comment]
I've got a few RPI's 3 around.. on a mission for a "coporate small biz project".. so this is possible..

Maybe we code in golang.. cos its not an imperterator..

Hardware..
We could emulate the in+outs as a FlightGear pilot/player.. and its flight dynamics

**Comment by pedromorgan** [comment]
Make lights switch on and off and annunication..

**Comment by klarkc** [comment]
Javascript port will be more awesome

**Comment by corvuscrypto** [comment]
> Javascript port will be more awesome

funny you should say that XD http://svtsim.com/moonjs/agc.html

**Comment by robertcatgithub** [comment]
you mean PERL ?

**Comment by Tropicalrambler** [comment]
We should replicate in JS,  Perl,  Python and every code...  then make the simulator GUI... Then an actual soce probe.  Raspberry Pi...  actually, there is a Space Simulator app on iTunes that shows how to use Noun and Verb on that computer...

**Comment by sundhaug92** [comment]
You could probably get it running more easily by compiling yaAGC (and family).

**Comment by Tropicalrambler** [comment]
We should set up the code, and get our own Apollo 17+ mission going,  in a smaller rocket and with a probe,  land near any of the previous missions and confirm previous excursions to the moon,  to prove the naysayers wrong.  Great thing to use the "original" program guidance...

**Comment by greysondn** [comment]
On a more serious note, in #19 a comment mentions the port is pointless without a compatible environment (ie; real world physics), but it only made me wonder if a "functional enough" physics simulation would enable this to run. For example, could you fabricate a game such that this code could be ran on an in-game lander module? And, if so, why could you not subsequently port the command logic to language X so long as it was compatible with host environment?

For all the joking around, I actually thought that'd be pretty cool.

**Comment by chrislgarry** [comment]
Go for it!

**Comment by indy91** [comment]
@greysondn You might want to check out our project here: http://nassp.sourceforge.net/wiki/Main_Page and https://github.com/dseagrav/NASSP We are running the Virtual AGC emulator (https://github.com/rburkey2005/virtualagc) as part of a simulation of the Apollo program.

**Comment by pedromorgan** [comment]
@greysondn re 
"without a compatible environment (ie; real world physics), but it only made me wonder if a "functional enough" physics simulation would enable this to run."

That is why I raise the Flightgear #71 issue as it has the "FDM" = Flight Dynamics Model and maths etc.. Maybe not in space, but certainly the Shuttle is still in development...
