### ISSUE TITLE
Set SCE to Auxiliary by default

### ISSUE THREAD

**Issue by cjmielke** [chrislgarry/Apollo-11#69]
This will greatly reduce power usage and greatly improve performance on malfunctioning hardware.

**Comment by sundhaug92** [comment]
Won't that just make the auxillary the primary and the primary the auxillary?

**Comment by cjmielke** [comment]
John Aaron, is that you?

**Comment by Joltron** [comment]
[SCE to AUX, what the hell is that?](https://youtu.be/eWQIryll8y8?t=131)
