### ISSUE TITLE
Question: relation between this repo and virtualagc?

### ISSUE THREAD

**Issue by lurch** [chrislgarry/Apollo-11#692]
Hi,

I see that https://github.com/virtualagc/virtualagc also has a bunch of source-code transcribed from the same image-scans, and http://www.ibiblio.org/apollo/faq.html#What_about_GitHub_Repositories in fact mentions this repo, and claims that their repo is more up-to-date now?

As a test, I compared https://github.com/chrislgarry/Apollo-11/blob/master/Comanche055/CONIC_SUBROUTINES.agc and https://github.com/virtualagc/virtualagc/blob/master/Comanche055/CONIC_SUBROUTINES.agc and by comparing the differences between the files against the scans at http://www.ibiblio.org/apollo/ScansForConversion/Comanche055/ I found that each of the files had (correct) fixes that the other file didn't have.
Is it "allowed" to use this method to spot mistakes this way, and then push relevant PRs to each of the projects; or is each project attempting to be a "clean room" conversion totally independent from the other project?

And to get the opinion from the "other side", pinging the people listed on https://github.com/orgs/virtualagc/people
@Niklasva @rburkey2005 @Schwarzy1 @steve1780 @Thymo-
BTW the virtualagc folks may also be interested in https://github.com/chrislgarry/Apollo-11/issues/690 - feel free to copy it and modify it however you please.

**Comment by wopian** [comment]
See https://github.com/chrislgarry/Apollo-11/issues/38 for prior discussion. 

I was unable to contribute much from 2017 onwards (from being one of the most active proofers) as I was at university, which I have finished this year and will be starting to go through the proofing issues once I've dealt with maintaining my other projects I've neglected over the years.

**Comment by rburkey2005** [comment]
@lurch Regarding #690, the Virtual AGC Project already provides colorized, hyperlinked HTML forms of all known-surviving AGC code.  For example, [the HTML for Luminary 99 is here](http://www.ibiblio.org/apollo/listings/Luminary099/MAIN.agc.html), and [the HTML for Comanche 55 is here](http://www.ibiblio.org/apollo/listings/Comanche055/MAIN.agc.html).  Perhaps #690 provides some advantage over the HTML already provided; if so, I admit that I haven't examined the PR closely enough to determine find out.

Historically, the AGC code transcriptions in _this_ repository originally came from the Virtual AGC Project transcriptions, but prior to the many Virtual AGC Project corrections you've discovered are present in the Virtual AGC repository _now_.  From the Virtual AGC side, the only interest is in the accuracy of the transcription: there is no interest in maintaining a clean room.  So, speaking just for the Virtual AGC Project, [PRs for problems in Virtual AGC transcriptions](https://github.com/virtualagc/virtualagc/issues) are certainly welcome.  (I have no insight as to whether PRs in the other direction are welcome.)

**Comment by wopian** [comment]
> @lurch Regarding #690, the Virtual AGC Project already provides colorized, hyperlinked HTML forms of all known-surviving AGC code. For example, the HTML for Luminary 99 is here, and the HTML for Comanche 55 is here. Perhaps #690 provides some advantage over the HTML already provided; if so, I admit that I haven't examined the PR closely enough to determine find out.

It's just displaying the scans in a quicker-to-navigate way. As opposed to opening multiple tabs or constantly editing the address bar while going through the pages to check for transcription issues.

> (I have no insight as to whether PRs in the other direction are welcome.)

Those are welcome too.

---

I think the overall goal as of now is to finish going through the [open proofing issues](https://github.com/chrislgarry/Apollo-11/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22) and once that is done diff against Virtual AGC (with the scans being the source of truth) to make sure we don't accidently re-introduce typos that were fixed on Virtual AGC but missed by us. Of course, diffing against Virtual AGC can be done in parallel to the continued proofing of the scans, so I don't mind either way.

I still need to check (locally) if `git merge --allow-unrelated-histories` from #38 will accomplish what we desire with maintaining commit attribution to chrislgarry/Apollo-11 and Virtual-AGC/Virtual-AGC contributors though.
