### ISSUE TITLE
The code to come back from moon has an issue. And now I am stuck in the moon.

### ISSUE THREAD

**Issue by amalChandran** [chrislgarry/Apollo-11#70]

**Comment by klarkc** [comment]
Try again later with the beta version

**Comment by robertcatgithub** [comment]
Find and run veg_advice.exe and see what happens

**Comment by gczuczy** [comment]
Have you tried to turn it off and turn it on again?

**Comment by feiming** [comment]
rename earth to moon and use goto moon function to get back.

**Comment by amalChandran** [comment]
@feiming Ill try this. If it works I will reply. Only if it works.

**Comment by akring** [comment]
Told you don't run the code on windows :)

**Comment by schneidermayer** [comment]
I got a bluescreen, thanks Bill Gates and NASA! Btw, when is the Android app coming out?

**Comment by gczuczy** [comment]
@schneidermayer  I think we still need some improvements to utilize NFC for controlling from an droid app.

**Comment by stefangeorg** [comment]
LGTM

**Comment by Alhadis** [comment]
ＡＢＳＯＬＵＴ ＲＯＦＬＦＩＴ.

<img src="https://cloud.githubusercontent.com/assets/2346707/16756425/4e395ea6-4848-11e6-83d3-2a2860859eff.jpg" />
