### ISSUE TITLE
FlightGear

### ISSUE THREAD

**Issue by pedromorgan** [chrislgarry/Apollo-11#71]
Its an open source flight sim..

And indeed an interesting model was the Shuttle..

Think that flightgear and this project could integrate..

Same stuff about "physics" et all.. 

https://sourceforge.net/projects/flightgear/

**Comment by indy91** [comment]
We already have such a project (https://github.com/dseagrav/NASSP) for the Orbiter Space Flight Simulator, which uses the Virtual AGC emulator (https://github.com/rburkey2005/virtualagc). If there ever is a similar project started for FlightGear, we will very gladly help where we can.

**Comment by pedromorgan** [comment]
For ref this is FG's space shuttle and stuff
http://wiki.flightgear.org/Space_Shuttle

BUt considered here as an idiot is the accent phase.. 
but I thing gravirty calcs et all are kinda there as an FDM (Flight Dynamics Model).. but I am only an idiot..

**Comment by pedromorgan** [comment]
All I am trying to suggest is that we "maybe" can use flightgear as an "input" the this code...not good explain tingz

**Comment by chrislgarry** [comment]
@pedromorgan feel free to mention this to the folks at FG. Also, check out what @indy91 has done. It would be a good starting point.
