### ISSUE TITLE
Can we put this installed in The International Space Station and China Tiangong 2 and ... ?

### ISSUE THREAD

**Issue by UnknownPowered** [chrislgarry/Apollo-11#74]
First, I must say, this is a very long story...

---------------------

After a long time of undercover, I joined the international space station and China Tiangong 2 Engineering Department, I'm applying to install Apollo-11 on them, The developer turned me down, on the grounds that:

The International Space Station said: For us, the Apollo-11 system is too complicated, because we are NOT using the best language ------ ASM, we only using the very best language all over the universe: PHHHP!!!
(Finally, they kicked me out. I was defeated by them ...)

中国天宫2号说：呵呵，真有趣。
China Tiangong 2 said: HE-HE, REALLY INTERESTING.
(... I know nothing about the power ...)

---------------------

Finally, I had to test myself, and then the result is:
**I'm stuck on the moon, HELP!!!!!!!!!!!!!! I saw UFO and Martian man ???!**

---------------------

The Martian said they were just passing by ...... And they also let me naked, and said it was a physical check. Then, there was a very long story ... 

---------------------

I declare that I give up my American citizenship and join the citizenship of Mars.

---------------------

..................................................

---------------------

**WaaaAAAAAAAAAAAaAaAAAAAaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaait a moment！ Did you forget about my problem? Can we put this installed in The International Space Station and China Tiangong 2 and ... ? Help me please !!!**

---------------------

**(!!!WARNING!!!: Of course, I am on behalf of the people of Mars to consult you, I hope you do not make foolish behavior, so as not to lead to the interstellar war.)**

**Comment by sourcepowered** [comment]
Woooooow, I'm stuck on the moon, too.
where are you? My coordinates is 12112° 2918' 12312'', 98696° 2142' 29184981''.
I'm repairing BUG, come and help me!

**Comment by MultiverseCore** [comment]
**你对力量一无所知！
You have no idea about POWERE!!!**

**Comment by chenenyu** [comment]
This story made me laugh and urine.

**Comment by rogersachan** [comment]
kek

**Comment by BingoZ** [comment]
A fool hat!

**Comment by pairochjulrat** [comment]
IoI

**Comment by loulousky** [comment]
alright you win

**Comment by tobatha** [comment]
best materials for a comedy movie by all means

**Comment by HuarenYu** [comment]
MDZZ

**Comment by AuthGood** [comment]
I think "MDZZ" 's chinese mean is: Mother is Retarded ?! ( This is a Chinese friend told me ... :P )

**Comment by loulousky** [comment]
妈的智障 MDZZ 正解

**Comment by AuthGood** [comment]
You joined the Mars nationality ??? Very Great !!! But ... I want to say:
**Did you see MATTDAMON???**

**Comment by xmfbit** [comment]
Hi, @AuthGood I think in Chinese, "妈的" is an exclamation and has no relationship with "Mother", which is "妈" in Chinese. :)

**Comment by AuthGood** [comment]
@xmfbit Oh sorry I know that and I delete it, this is my fault.. Let we delete the comment. I will delete this, don't let other people make a mistake.

**Comment by mak3103** [comment]
Hang on there....the ones who let you remove your clothes are not martians. They are indians who just look like that on moon. Btw, I hope they didnt took away your $'s. 
Also, here is a workaround for your ask - tilt the spaceship a bit and fire the gas. It will work like a charm. Cheers!

**Comment by feiming** [comment]
it work in virtual space station

**Comment by dongyado** [comment]
yeah, lmao

**Comment by thomasren212** [comment]
Wish you best of luck, EXCITED! +1s

**Comment by zixiliuyue** [comment]
good  good good

**Comment by KingYoung87** [comment]
please call 110 or 911.

**Comment by 312362115** [comment]
???

**Comment by M0xkLurk3r** [comment]
Amazing in your fantasy fiction ...! And aliens may hides in internet of our planet, searching their lace news and fictions, and they may already read your issue. I could believe that they hates people discuss their likes Slender man so make sure your window locked before sleeping or you may be kidnapped by UFO LOL

**Comment by viohex** [comment]
你的脑洞还可以啊

**Comment by damoqiongqiu** [comment]
666

**Comment by lazy1523** [comment]
hahahahahaa,really  interesting

**Comment by h0nes1pr09rammer** [comment]
写的啥子

**Comment by wzpan** [comment]
I successfully installed it into my calculator and it was burned after 10 seconds.

**Comment by qwordy** [comment]
一颗赛艇

**Comment by darf2k** [comment]
233333333～(You win! But don't you even know what these code means for Chinese~^O^)
