### ISSUE TITLE
Question: Mod history at the beginning of files.

### ISSUE THREAD

**Issue by Atknssl** [chrislgarry/Apollo-11#777]
At the beginning of source codes, there is a mod history section annotating changes made in that file. As we proof these files, we make changes. Should we update mod history too?

**Comment by oldmud0** [comment]
Nope, those just denote corrections made during the Virtual AGC project - these days version control (Git history) has superseded that.

**Comment by wopian** [comment]
No, [Git's blame](https://git-scm.com/docs/git-blame) and commit histories cover the changes here. The mod history is from Virtual AGC which we will be merging back into once Comanche and Luminary are fully proofed (see https://github.com/chrislgarry/Apollo-11/issues/38)
