### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by pwnsdx** [chrislgarry/Apollo-11#8]
![i-dont-want-to-live-on-this-planet](https://cloud.githubusercontent.com/assets/2057765/16673843/1e4a9c08-44b2-11e6-937b-c2b869758eae.jpg)

**Comment by apfeltee** [comment]
Some kind of introduction as to what each file does (apart from the filenames, obviously) would be a great start.
Otherwise, I think it's mostly just to look at. These kind of computers predate even ancient machines like pdp11, I think.

**Comment by s-chizhik** [comment]
Need `Makefile`, i guess.

**Comment by TheOssi** [comment]
Well first of all you need to get to National Air & Space Museum, Washington, D.C. and borrow the command module. Then you need a rocket and a launch permission, i guess. Please consider also hiring a good lawyer.

**Comment by pwnsdx** [comment]
Thanks for the answers but is it free to launch a rocket? Food and lawyers are pretty expensive already

**Comment by TheOssi** [comment]
@nasa

**Comment by CamW** [comment]
Source files refer to http://www.ibiblio.org/apollo which is all about a Virtual AGC - LVDC - Gemini project and talks about a simulated AGC CPU. So that's probably the best place to start.

**Comment by moloned** [comment]
you could try the AGC simulator http://svtsim.com/moonjs/agc.html

**Comment by moloned** [comment]
I'd love to see a hackathon today to see how close modern programmers would get to running this software within the resources of the AGC (2MHz 16-bit machine with 2kB memory https://en.wikipedia.org/wiki/Apollo_Guidance_Computer)

**Comment by ZiTAL** [comment]
first buy a spaceship :_D

**Comment by 409H** [comment]
Can anyone help me install this on my Apollo 11 set? A rough guide if anything. Below is a picture of my set-up.

![https://dp1eoqdp1qht7.cloudfront.net/community/projects/7b5/24e/76841/1562933-o_18vmhs3t8tivs4a1vuh15mk1s95c-full.jpg](https://dp1eoqdp1qht7.cloudfront.net/community/projects/7b5/24e/76841/1562933-o_18vmhs3t8tivs4a1vuh15mk1s95c-full.jpg)

**Comment by jpetters** [comment]
Look on ebay for a second hand spaceship? :smile: :rocket:

**Comment by sw00** [comment]
This is a great startup idea if anyone is willing to take it up - Rockets as a Service (RaaS). Give users the ability to launch rockets as needed.

**Comment by brianknight10** [comment]
This could be the start of "Uber for Rockets"

**Comment by thefailtheory** [comment]
For me, the table codes for react buttons at the moment in Appolo code is this
:+1:
:-1: !land
:smile:
:confused: wtf?
:tada:
:heart: O2

https://jsfiddle.net/hymk95xm/

**Comment by timmitra** [comment]
That's how the suck you in. The software is free but the required hardware is expensive. [fires up the 3D printer]

**Comment by BrunoCoutinho** [comment]
@brianknight10 "Uber for Rockets" already exists: http://www.spacex.com/

**Comment by aguasvivasclass** [comment]
We can share this code with the guys from #Area51 and see if we can get a couple of "drones" borrowed to try it.

**Comment by cirosantilli** [comment]
fpga implementation in progress https://github.com/Obijuan/ACC

**Comment by oldmud0** [comment]
Who will help knit the core memory?
