### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by jessevanmuijden** [chrislgarry/Apollo-11#81]
We should start thinking about writing some tests.

**Comment by amin007** [comment]
What are you want to test?

**Comment by Wizzercn** [comment]
大家好~~

**Comment by chshouyu** [comment]
Test if these code can send me to moon or not.

**Comment by iURWang** [comment]
I have been on the moon.hahahahaha~

**Comment by DheerendraRathor** [comment]
I built my own Apollo system and Saturn V rocket. Somehow I convinced MIT to get me some rope memories to install this module!

Hello from the moon!
