### ISSUE TITLE
Accessing Luminary099/TRIM_GIMBAL_CNTROL_SYSTEM.agc returns 404

### ISSUE THREAD

**Issue by cwoerner** [chrislgarry/Apollo-11#893]
The following source file yields a 404 when navigating within github:

https://github.com/chrislgarry/Apollo-11/blob/master/Luminary099/TRIM_GIMBAL_CNTROL_SYSTEM.agc

**Comment by wopian** [comment]
It is https://github.com/chrislgarry/Apollo-11/blob/master/Luminary099/TRIM_GIMBAL_CONTROL_SYSTEM.agc

Where is the broken link linked from?

**Comment by dineshnagarit** [comment]
@wopian @cwoerner please review the PR https://github.com/chrislgarry/Apollo-11/pull/900 , It includes the changes for correct url updation at Luminary099/READ.md

**Comment by thishura** [comment]
> The following source file yields a 404 when navigating within github:
> 
> https://github.com/chrislgarry/Apollo-11/blob/master/Luminary099/TRIM_GIMBAL_CNTROL_SYSTEM.agc

It is TRIM_GIMBAL_CONTROL_SYSTEM.agc insted of TRIM_GIMBAL_CNTROL_SYSTEM.agc
