### ISSUE TITLE
Error: no wizard found

### ISSUE THREAD

**Issue by ResidentMario** [chrislgarry/Apollo-11#9]
[These have got to be the most epic lines of code of all time](https://github.com/chrislgarry/Apollo-11/blob/master/THE_LUNAR_LANDING.s#L254)&mdash;from `THE_LUNAR_LANDING.s`:

![2016-07-08 00_37_46-apollo-11_the_lunar_landing s at master chrislgarry_apollo-11](https://cloud.githubusercontent.com/assets/3466341/16677511/d8bd7410-44a4-11e6-93c3-1dc53a15670b.png)

**Comment by thefailtheory** [comment]
Is there any more infos on the instructions ? or a link to a documentation to see how it works ?

**Comment by chrislgarry** [comment]
There never was a wizard.
