### ISSUE TITLE
Is this a spelling typo?

### ISSUE THREAD

**Issue by mykeTheArchAngel** [chrislgarry/Apollo-11#913]
This file called attitude_maneuver_routine.agc , isn't it supposed to be altitude_maneuver_routine.agc instead or am I missing something here?

**Comment by tommairs** [comment]
I am fairly certain the file name is correct. 
"KALCMANU IS A ROUTINE WHICH GENERATES COMMANDS FOR THE LM DAP TO CHANGE THE ATTITUDE OF THE SPACECRAFT
# DURING FREE FALL. "

**Comment by wopian** [comment]
They're very similar words but they refer to different things! 😊

Altitude is distance to sea level

Attitude is the orientation of an aircraft/spacecraft  (pitch/roll/yaw)

https://en.m.wikipedia.org/wiki/Spacecraft_attitude_control

**Comment by mykeTheArchAngel** [comment]
Thank you for enlightening me on this. Sorry for coming off as ignorant @wopian @tommairs.

**Comment by wopian** [comment]
You didn't come off as ignorant!
