### ISSUE TITLE
Is it possible for a file to contain all of the source code instead of in seperate files?

### ISSUE THREAD

**Issue by BEG5210** [chrislgarry/Apollo-11#917]
I just want to be able to view it all in one file, with seperators or something distinguishing each file from the next.

**Comment by andrewrump** [comment]
That is not the goal of GitHub. Make a script/program which does that for you. It is easy to do - if you know how to program.

**Comment by BEG5210** [comment]
> That is not the goal of GitHub. Make a script/program which does that for you. It is easy to do - if you know how to program or ask someone to do it.

My apologies. Im new to GitHub and stuff, so please forgive me for that.
