### ISSUE TITLE
How do I build and run?

### ISSUE THREAD

**Issue by swiftc-org** [chrislgarry/Apollo-11#94]
I don't know which compiler could build it and what device could run it (I don't have a Apollo)

**Comment by schneidermayer** [comment]
Maybe there is a Apollo 11 VM? ;-)

**Comment by matas2007** [comment]
There is an emulator: http://www.ibiblio.org/apollo/

**Comment by oznogon** [comment]
Indeed, Virtual AGC is the source of this transcription. See http://github.com/rburkey2005/virtualagc.

**Comment by RafaelC457ro** [comment]
I don't know how build, but, you can run the javascript version: http://svtsim.com/moonjs/agc.html

**Comment by chrislgarry** [comment]
@swiftc-org check out @oznogon 's comment.

**Comment by Zerquix18** [comment]
You can buy a starship on eBay

**Comment by kriptonis** [comment]
How awesome would it be to have the emulator connected to a game engine where we could actually interact with the Apolo 11?
