### ISSUE TITLE
Error, "Cannot open pod bay doors"

### ISSUE THREAD

**Issue by bretlowery** [chrislgarry/Apollo-11#98]
Installed and successfully built on HAL 9000 RC 1. Subsequently went on EVA without space helmet, on return asked HAL to open pod bay doors, says he cannot. We are currently arguing about this; extremely poor customer service from HAL after this install (is there a conf setting I missed?)

**Comment by lkraider** [comment]
Tried on-site modification of some of the HAL modules, it started to error out with messages like "I'm afraid", "My mind is going.", "I can feel it.". Way to support user mods dev team.

**Comment by rhaleblian** [comment]
This was closed for the wrong reason.
It could only have been attributed to human error.
